### ISSUE TITLE
System tray in Unity

### ISSUE THREAD

**Issue by muammar** [muammar/mkchromecast#10]
I have received some reports that the system tray icon is not working if you are under Unity. I will try to fix this problem after I install Ubuntu in a virtual machine. 

See: 
1.https://plus.google.com/+MadsHansen/posts/9uebVwDTaR2

**Comment by jymbob** [comment]
Working here:
![selection_011](https://cloud.githubusercontent.com/assets/4148501/17701094/52e1a556-63c0-11e6-891f-1ad889f11020.png)
![menu_013](https://cloud.githubusercontent.com/assets/4148501/17701080/46d81e8e-63c0-11e6-899f-2383c8243ca0.png)

Installed from deb, then used apt to install pyQt5

**Comment by muammar** [comment]
Thanks for the information. I have added now python-pyqt5 explicitly to the dependencies instead of being a suggested package. 

https://github.com/muammar/mkchromecast/blob/debian/debian/control

**Comment by muammar** [comment]
I have tested myself. `mkchromecast` works in Unity. 

![virtualbox_ubuntu_21_08_2016_15_23_56](https://cloud.githubusercontent.com/assets/954209/17837450/9b91183a-67b3-11e6-96e1-279ffc695ac3.png)

I am proceeding to close this bug.

**Comment by softvision-sergiulogigan** [comment]
Hi, @muammar 
I tried installing this app on Linux Mint 18.2, and I still get the Dependency error.
Could you please help?

![screenshot from 2017-07-10 20-10-29](https://user-images.githubusercontent.com/16573771/28030446-75cb5dd4-65ac-11e7-85ec-7b75d3cfed1d.png)

**Comment by muammar** [comment]
@softvision-sergiulogigan You need  `python-pychromecast`. Try installing it from here: https://packages.ubuntu.com/yakkety/python-pychromecast.

**Comment by IWantOriginalName** [comment]
Hi! I Install your mkcromecast on Manjaro (Arch Linux). All working, but I have delay over 1 minute... What can I fix it?

**Comment by Bonteruel** [comment]
Hi. I tried on debian 11 cinnamon, and the desktop is not casted. I think you said you have installed debian. Which desktop environment do you use?
