### ISSUE TITLE
[Enhancement] [macOs] white menu bar icon for black menu bar theme

### ISSUE THREAD

**Issue by mpede** [muammar/mkchromecast#101]
It would be great to be able to change the menu bar icons to white if you are using the dark menu bar theme. Currently the icon is invisible on the dark menu bar.

**Comment by muammar** [comment]
It is possible to change the colors of the icons from black to white. Check in the preferences. You have to perform some action (like searching) to see the change in effect. Let me know if it works for you.

**Comment by mpede** [comment]
Oh my word - how could I have missed that. Thanks so much for pointing it out! It worked after I quit and restarted the app.
