### ISSUE TITLE
error installing from source

### ISSUE THREAD

**Issue by ashleybeshir** [muammar/mkchromecast#110]
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-puaxh6as/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-khrjy670-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-puaxh6as/netifaces/

pip and setuptools are up to date

**Comment by muammar** [comment]
@ashleybeshir to have this package installed from sources, what you have to do is to clone the repository, install the modules in the `requirements.txt` file, get into the `mkchromecast` directory and execute: `python mkchromecast.py`. You could also create a symlink of mkchromecast.py in your PATH for binaries.

**Comment by ashleybeshir** [comment]
@muammar i did what u said but the netifaces package gives this error when trying to install 
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p8o8zgt0/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-f5eic_hn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-p8o8zgt0/netifaces/

**Comment by muammar** [comment]
Can you describe how are trying to install it?

**Comment by ashleybeshir** [comment]
pip install 'netifaces==0.10.4'
pip and setup tools are up to date

**Comment by muammar** [comment]
Have you tried installing a newer version of `netifaces`?

`pip install netifaces`

**Comment by muammar** [comment]
I will proceed to close this report. Feel free to reopen it if needed. Best.
