### ISSUE TITLE
No audio for certain video files

### ISSUE THREAD

**Issue by plepore** [muammar/mkchromecast#111]
Hi there.  I'm able to cast video and audio on linux using node, however audio won't stream for certain videos I have.  I'm thinking these certain video files have an audio track that mkchromecast can't deal with.  Is there a list of supposed to audio for video files that I can look at so I can ensure I have the correct format in my video files?

**Comment by plepore** [comment]
I looked into this further and it appears chromecast can't play audio from mkv files which is what I have.  I guess I'll convert my files.  Sorry for the bug spam.

**Comment by muammar** [comment]
Hi, I had noticed this before. I think if you use node backend sometimes it works. You could try that if you want.
