### ISSUE TITLE
App doesn't show up

### ISSUE THREAD

**Issue by codeyhere** [muammar/mkchromecast#112]
Hey, i have installed the app by dmg and after that also by homebrew.

When I execute the app, it appears in my dock, but there is nothing started. Like there is no icon in my tray icon.

I do use MacOS 10.13.

I would be very thankful.

**Comment by codeyhere** [comment]
Ah, okay I found it. It's transparent on my bar. So you just have to click blind on the bar and have to imagine that's it's there. When you click on it, it appears.

Anyway, it would be great if you could fix it.

**Comment by muammar** [comment]
Would you mind sending a screenshot?

**Comment by codeyhere** [comment]
It is already fixed as i searched it for first time blind. Thank you anyway.
