### ISSUE TITLE
Cannot install PyQt5

### ISSUE THREAD

**Issue by josefs** [muammar/mkchromecast#114]
When I do `pip install -r requirements.txt` I get the following error at the end of the output:
```
  Could not find a version that satisfies the requirement PyQt5==5.8.2 (from -r requirements.txt (line 8)) (from versions: )
No matching distribution found for PyQt5==5.8.2 (from -r requirements.txt (line 8))
```
All the other packages seem to be installing just fine.

**Comment by muammar** [comment]
It should be then: `pip install PyQt5==5.9`. Does that work for you? I should upgrade the `requirements.txt`.

**Comment by josefs** [comment]
That doesn't work either.
I assume there's some kind of error on my side but given that I can install the other packages I can't figure out what the problem is.

**Comment by muammar** [comment]
@josefs it is just something about PyQt5. Sometimes one can install it using `pip` and some other times it just does not work. The best way of installing PyQt5, and I forgot to ask about your OS, would be `brew` (macOS) or your package manager in Linux. 


```
muammar@zarathustra ~/github/mkchromecast [devel]
± % pip install PyQt5==5.9                                                                                                                                                                                                             !10429
Collecting PyQt5==5.9
  Could not find a version that satisfies the requirement PyQt5==5.9 (from versions: )
No matching distribution found for PyQt5==5.9```

**Comment by josefs** [comment]
Ok, I installed PyQt5 using `apt-get` (I'm running Ubuntu)
Thanks a lot for the help!

**Comment by muammar** [comment]
You are welcome. Feel free to reopen this report. Best.
