### ISSUE TITLE
can't launch mkchromecast

### ISSUE THREAD

**Issue by fondthierry** [muammar/mkchromecast#115]
Hi 

i try to install mkchromecast from source ( deb doesn't match) 

Distributor ID:	LinuxMint
Description:	Linux Mint 17.3 Rosa
Release:	17.3
Codename:	rosa

I have installed python 3 and from directory mkchromecast launch " python3  mkchromecast.py" and when needed "sudo pip3 install ...." 

now i get this message 

Mkchromecast v0.3.7.1
:::cast::: sockets method 192.168.1.35
:::audio::: chunk_size:  1024
:::audio::: Program /usr/bin/parec found in /usr/bin/parec
:::audio::: backend dictionary {'/usr/bin/parec': 'parec', 'parec': 'parec'}
Selected backend: /usr/bin/parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz
:::audio::: command ['lame', '-b', '192', '-r', '-']
:::cast::: sockets method 192.168.1.35
:::systray::: self.notifications disabled
:::systray::: self.searchatlaunch disabled
:::systray::: self.colors black
:::systray::: Screen resolution:  1280 800
:::systray::: High-DPI screen detected...

what can i do ??

I'm not a specialist of python 

best regards 

fondthierry

**Comment by muammar** [comment]
When doing so, you should find in pavucontrol an `MKchromecast` sink that you have to choose in order to cast your audio. Can you see it?

**Comment by fondthierry** [comment]
I try


2017-11-03 19:11 GMT+01:00 Muammar El Khatib <notifications@github.com>:

**Comment by fondthierry** [comment]
can you help me for pavucontrol what have I to do ?

2017-11-03 19:12 GMT+01:00 Dominique Oudin <dominiqueoudin@gmail.com>:

**Comment by fondthierry** [comment]
I see your gif (link ) but i don't know how to do for opening  pavu
control  and select the mkchromecast sink

https://raw.githubusercontent.com/muammar/mkchromecast/master/images/mkchromecast_linux.gif

2017-11-03 19:20 GMT+01:00 Dominique Oudin <dominiqueoudin@gmail.com>:

**Comment by muammar** [comment]
> On Nov 3, 2017, at 15:13, fondthierry <notifications@github.com> wrote:
> 
> I see your gif (link ) but i don't know how to do for opening pavu
> control and select the mkchromecast sink

You can install it from here: 

https://community.linuxmint.com/software/view/pavucontrol


And then you can open it from the terminal by executing `pavucontrol`
-- 
Muammar El Khatib.
http://muammar.me

**Comment by fondthierry** [comment]
I do so  before , but i don't see where  i can do something for mk
chromecast on pavucontrol interface

2017-11-03 20:17 GMT+01:00 Muammar El Khatib <notifications@github.com>:

**Comment by fondthierry** [comment]
perhaps with terminal commands  but i don't know which


2017-11-03 20:17 GMT+01:00 Muammar El Khatib <notifications@github.com>:

**Comment by fondthierry** [comment]
now i don't have my google chromecast i'm waiting for it

2017-11-03 20:28 GMT+01:00 Dominique Oudin <dominiqueoudin@gmail.com>:

> I do so  before , but i don't see where  i can do something for mk
> chromecast on pavucontrol interface
>
> 2017-11-03 20:17 GMT+01:00 Muammar El Khatib <notifications@github.com>:
>

**Comment by fondthierry** [comment]
I'm looking for adding a new sink called mkchromecast  in pulseaudio before
lauching  pavucontrol  am I right ?


2017-11-03 20:32 GMT+01:00 Dominique Oudin <dominiqueoudin@gmail.com>:

**Comment by muammar** [comment]
> On Nov 3, 2017, at 16:05, fondthierry <notifications@github.com> wrote:
> 
> I'm looking for adding a new sink called mkchromecast in pulseaudio before
> lauching pavucontrol am I right ?


No. The first thing you have to do is launch Mkchromecast in the terminal.
After you do so, the sink will be automatically created. Of course, if
Mkchromecast is not connected to any chromecast then it implies that when it
shuts down it will delete the sink.

**Comment by fondthierry** [comment]
ok  so i'm waiting for my chromecast

thanks for all


2017-11-03 21:12 GMT+01:00 Muammar El Khatib <notifications@github.com>:
