### ISSUE TITLE
casting internet radio stream fails, leaves chromecast device in cast mode

### ISSUE THREAD

**Issue by dhdurgee** [muammar/mkchromecast#116]
I just installed your package on my linux mint 18.2 x64 cinnamon system and made my first attempt to use it.  It failed.  The terminal session shows:

dhdurgee@Z560 ~/bin $ mkchromecast --source-url http://19023.live.streamtheworld.com:80/WWRCAMAAC_SC
Mkchromecast v0.3.7
 
List of Devices Available in your Network:
------------------------------------------

Index 	Types 	Friendly Name 
===== 	===== 	============= 
0 	Gcast 	WD32FB2530
 
We will cast to first device in the list above!
 
WD32FB2530
 
The IP of WD32FB2530 is: 192.168.230.2
Your local IP is: 192.168.230.233
 
Casting from stream URL: http://19023.live.streamtheworld.com:80/WWRCAMAAC_SC
Using media type: audio/mpeg
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 270, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 51, in __init__
    self.audio_linux()
  File "/usr/bin/mkchromecast", line 78, in audio_linux
    self.cc.play_cast()
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 343, in play_cast
    media_controller.play_media(self.sourceurl, mtype, title=self.title)
  File "/usr/lib/python2.7/dist-packages/pychromecast/controllers/media.py", line 416, in play_media
    msg['customData']['payload']['title'] = title
KeyError: 'payload'
dhdurgee@Z560 ~/bin $ 

As I noted on the subject line, not only did this fail, it left the device in cast mode.  I would have expected a handler to have exited cast mode cleanly in case of an error.

Can I provide any further information?  Did I miss something?

Dave

**Comment by muammar** [comment]
Can you try specifying a codec? Example:

`mkchromecast --source-url http://19023.live.streamtheworld.com:80/WWRCAMAAC_SC -c mp3`.

**Comment by dhdurgee** [comment]
As requested:

dhdurgee@Z560 ~/bin $ mkchromecast --source-url http://15113.live.streamtheworld.com:80/WMALFMAAC_SC -c mp3
Mkchromecast v0.3.7
 
List of Devices Available in your Network:
------------------------------------------

Index 	Types 	Friendly Name 
===== 	===== 	============= 
0 	Gcast 	WD32FB2530
 
We will cast to first device in the list above!
 
WD32FB2530
 
The IP of WD32FB2530 is: 192.168.230.2
Your local IP is: 192.168.230.233
 
Casting from stream URL: http://15113.live.streamtheworld.com:80/WMALFMAAC_SC
Using media type: audio/mpeg
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 270, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 51, in __init__
    self.audio_linux()
  File "/usr/bin/mkchromecast", line 78, in audio_linux
    self.cc.play_cast()
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 343, in play_cast
    media_controller.play_media(self.sourceurl, mtype, title=self.title)
  File "/usr/lib/python2.7/dist-packages/pychromecast/controllers/media.py", line 416, in play_media
    msg['customData']['payload']['title'] = title
KeyError: 'payload'
dhdurgee@Z560 ~/bin $ mkchromecast --source-url http://15113.live.streamtheworld.com:80/WMALFMAAC_SC -c aac
Mkchromecast v0.3.7
 
List of Devices Available in your Network:
------------------------------------------

Index 	Types 	Friendly Name 
===== 	===== 	============= 
0 	Gcast 	WD32FB2530
 
We will cast to first device in the list above!
 
WD32FB2530
 
The IP of WD32FB2530 is: 192.168.230.2
Your local IP is: 192.168.230.233
 
Casting from stream URL: http://15113.live.streamtheworld.com:80/WMALFMAAC_SC
Using media type: audio/aac
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 270, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 51, in __init__
    self.audio_linux()
  File "/usr/bin/mkchromecast", line 78, in audio_linux
    self.cc.play_cast()
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 343, in play_cast
    media_controller.play_media(self.sourceurl, mtype, title=self.title)
  File "/usr/lib/python2.7/dist-packages/pychromecast/controllers/media.py", line 416, in play_media
    msg['customData']['payload']['title'] = title
KeyError: 'payload'
dhdurgee@Z560 ~/bin $ 

Dave

**Comment by muammar** [comment]
This is working for me in both Linux and macOS. What version of pychromecast are you using?

**Comment by dhdurgee** [comment]
I am using version 0.6.12-0ubuntu3 from the JMita ppa here.  As I noted above, I am running mint 18.2, which is based on ubuntu xenial.  From what I can see the later version is on ubuntu zesty.

If it would be safe to do so, I could install the zesty version by placing it in my local repository.  My problem then would be keeping up with any updates to it.  I see it is now available in multiple python versions as well.

**Comment by muammar** [comment]
> On Nov 18, 2017, at 19:40, dhdurgee <notifications@github.com> wrote:
> 
> I am using version 0.6.12-0ubuntu3 from the JMita ppa here. As I noted
> above, I am running mint 18.2, which is based on ubuntu xenial


Try to update pychromecast to something newer. That would fix the problem
you are getting I guess.

**Comment by dhdurgee** [comment]
I downloaded pychromecast 0.7.3-3 from the zesty repository and added it to my local repository to allow me to update it.  After doing so your package appears to be working as you suspected.

Now that it is running I tried your -t option.  This left me with a few questions.  First, when I right clicked on the mkchromecast button in the tray and selected the "check for updates" I was told that I could download 0.3.7.1 to update.  I am running 0.3.7.1, so this is a puzzle.

Another puzzle is that if I call mkchromecast in tray mode, how do I open a stream?  I don't see a menu choice there for this.

**Comment by dhdurgee** [comment]
Just had another thought, perhaps for audio-only streams there is a way to leave the default google screen saver up as opposed to your screen?  The google screen saver has useful time and weather included as well as more visually pleasing images.

**Comment by muammar** [comment]
> I downloaded pychromecast 0.7.3-3 from the zesty repository and added it to my local repository to allow me to update it. After doing so your package appears to be working as you suspected.

Perfect. 

>Now that it is running I tried your -t option. This left me with a few questions. First, when I right clicked on the mkchromecast button in the tray and selected the "check for updates" I was told that I could download 0.3.7.1 to update. I am running 0.3.7.1, so this is a puzzle.

Don't pay too much attention to that message. It was a problem I had when I uploaded the package to Debian. For next releases that would be fixed. 

> Another puzzle is that if I call mkchromecast in tray mode, how do I open a stream? I don't see a menu choice there for this.

There is no option for that still. It should be added.

**Comment by muammar** [comment]
> Just had another thought, perhaps for audio-only streams there is a way to leave the default google screen saver up as opposed to your screen? The google screen saver has useful time and weather included as well as more visually pleasing images.

That is a good question. I would say that it is not possible. When I cast from Spotify to my TV I see this: 

![img_20171118_212647](https://user-images.githubusercontent.com/954209/32986795-5ae2cf4a-cca7-11e7-8030-216474bfe4db.jpg)

**Comment by dhdurgee** [comment]
On the tray option, I should also note that I get a segfault when I quit there:

dhdurgee@Z560 ~/Downloads $ cat /var/log/kern.log | grep mkchromecast
Nov 18 21:01:43 Z560 kernel: [432086.492491] mkchromecast[23251]: segfault at 8 ip 00007f2384c297d5 sp 00007fffb0fa7a50 error 4 in libQt5Widgets.so.5.5.1[7f2384a90000+659000]
Nov 18 21:06:35 Z560 kernel: [432378.249279] mkchromecast[23340]: segfault at 8 ip 00007f34a331c7d5 sp 00007ffd9ba5f670 error 4 in libQt5Widgets.so.5.5.1[7f34a3183000+659000]
Nov 18 21:26:25 Z560 kernel: [433567.800678] mkchromecast[24287]: segfault at 8 ip 00007fcb3a8f47d5 sp 00007fff3f2ad240 error 4 in libQt5Widgets.so.5.5.1[7fcb3a75b000+659000]
Nov 19 07:08:49 Z560 kernel: [468508.465969] mkchromecast[32459]: segfault at 8 ip 00007f6f492307d5 sp 00007ffface88170 error 4 in libQt5Widgets.so.5.5.1[7f6f49097000+659000]
dhdurgee@Z560 ~/Downloads $
