### ISSUE TITLE
When will the next release come out? How can we help?

### ISSUE THREAD

**Issue by sambokai** [muammar/mkchromecast#117]
Hi, 
Thanks for your work guys.

1. When will the next version be released? 
2. Are there any blocking issues that would need more attention?

I'm especially interested in the "fix" that hides the app icon from dock and alt-tab-switcher.

**Comment by muammar** [comment]
@sambokai thanks for your interest in this application!. These are the issues blocking the release: https://github.com/muammar/mkchromecast/milestone/2. What is holding back everything is the lack of time from my part :(. I would be very happy to receive PR to get it done.

**Comment by sambokai** [comment]
Alright, i think we should go through the issue backlog and clean it up a bit. Do you agree?

**Comment by muammar** [comment]
On Sun, Nov 19, 2017 at 5:58 AM, Sam Bokai <notifications@github.com> wrote:

> Alright, i think we should go through the issue backlog and clean it up a
> bit. Do you agree?
>

Hi Sam. Yes, thank you. I agree!


-- 
Muammar El Khatib.
http://muammar.me

**Comment by muammar** [comment]
@sambokai I have released `0.3.8.1`. I will close this report. Thank you for your interested! Best.
