### ISSUE TITLE
Problem with 480p

### ISSUE THREAD

**Issue by davidmartinezm** [muammar/mkchromecast#119]
Hi,

When launching mkchromecast with "--resolution 480p" on Ubuntu 17.10, it fails with the error "width not divisible by 2 (853x480)".
Would there be any problem on changing the 480p resolution to be 854x480 instead?

Thanks!

**Comment by muammar** [comment]
I have changed that. Thanks for reporting. Let me know if that solves the problem for you, and feel free to reopen this issue.

**Comment by davidmartinezm** [comment]
I installed mkchromecast with the deb package so I cannot simply pull the latest version. But I modified directly the py file to set 854 instead of 853 and it worked, so your commit should also work.

Many thanks!
