### ISSUE TITLE
Allow customising server port

### ISSUE THREAD

**Issue by RunasSudo** [muammar/mkchromecast#122]
Port 5000 is often used by applications on my system. It would be great to be able to configure mkchromecast to use a different port to avoid these conflicts.

**Comment by muammar** [comment]
I have pushed to `devel` a change that should allow customizing the server port. Can you try and let me know if it works for you?.

**Comment by RunasSudo** [comment]
@muammar Thanks for the reply – with devel, I'm getting an error on attempting to play audio through the Mkchromecast sink:

```
The IP of Dining room speaker is: X.X.X.X
Your local IP is: X.X.X.X
 
The media type string used is: audio/mpeg
Traceback (most recent call last):
  File "mkchromecast.py", line 273, in <module>
    mk()
  File "mkchromecast.py", line 53, in __init__
    self.audio_linux()
  File "mkchromecast.py", line 73, in audio_linux
    self.cc.play_cast()
  File "/home/runassudo/git/mkchromecast/mkchromecast/cast.py", line 378, in play_cast
    'http://' + localip + ':' + self.port + '/stream',
TypeError: must be str, not int
```

**Comment by muammar** [comment]
It should be fixed now. Did it work?

**Comment by RunasSudo** [comment]
@muammar Working perfectly now! 👍
