### ISSUE TITLE
[Errno 98] Address already in use

### ISSUE THREAD

**Issue by lzsolo** [muammar/mkchromecast#126]
Dear Muammar,

I like to use my chromecast device, but i get this message:
Mkchromecast v0.3.8.1
Starting Video Cast Process...
PID of main process: 4181
PID of streaming process: 4185
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/mkchromecast/mkchromecast/video.py", line 233, in start_app
    app.run(host='0.0.0.0', port=port, threaded=True)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 625, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 603, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 506, in make_server
    passthrough_errors, ssl_context)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	Családi szoba
 
Casting to first device shown above!
Select devices by using the -s flag.
 
Családi szoba
 
 
Information about  Családi szoba
 
DeviceStatus(friendly_name='Családi szoba', model_name='Chromecast', manufacturer='Google Inc.', api_version=(1, 0), uuid=UUID('e601119c-4088-112b-10be-fd20797cbfbc'), cast_type='cast')
 
Status of device  Családi szoba
 
CastStatus(is_active_input=False, is_stand_by=True, volume_level=1.0, volume_muted=False, app_id='E8C28D3C', display_name='Backdrop', namespaces=['urn:x-cast:com.google.cast.debugoverlay', 'urn:x-cast:com.google.cast.cac', 'urn:x-cast:com.google.cast.sse'], session_id='afd21a5b-2d70-4acd-90e8-5cf970f6d7a1', transport_id='afd21a5b-2d70-4acd-90e8-5cf970f6d7a1', status_text='')
 
The IP of Családi szoba is: 192.168.1.72
Your local IP is: 192.168.1.69
 
The media type string used is: video/mp4
 
Cast media controller status
 
CastStatus(is_active_input=False, is_stand_by=True, volume_level=1.0, volume_muted=False, app_id='CC1AD845', display_name='Default Media Receiver', namespaces=['urn:x-cast:com.google.cast.debugoverlay', 'urn:x-cast:com.google.cast.broadcast', 'urn:x-cast:com.google.cast.media'], session_id='5a7201ce-7520-4337-87d1-b3c2694346ce', transport_id='5a7201ce-7520-4337-87d1-b3c2694346ce', status_text='Ready To Cast')
 
Remember to open pavucontrol and select the mkchromecast sink.

Ctrl-C to kill the Application at any Time

------
What is the problem?

Thx,
Zsolt

**Comment by polyzen** [comment]
Seems like you already have something serving on that port. Have you tried visiting http://0.0.0.0:5000/?

**Comment by lzsolo** [comment]
Yes.
"Adress is invalid"

**Comment by polyzen** [comment]
Perhaps you could try `ss -nt dst :5000`?

**Comment by muammar** [comment]
Hi @lzsolo, as @polyzen suggested, it seems to be the case that you have already running on port ` 5000`. In this release, I introduced a new flag called ` --port`  (or just ` -p` for short) that you can use to specify another port. It is not yet added to the systray (for a new release). Append to your command `--port 5001`. Something like:

` ` ` 
mkchromecast --port 5001 -c ogg -b 320 
` ` ` ` 

And let us know if it works.

**Comment by lzsolo** [comment]
Hi @muammar,
It's working, but only youtube videos. When I want to play mp4/mp3 files, happend noting.
"192.168.1.72 - - [25/Dec/2017 20:35:07] "GET /stream HTTP/1.1" 500 -"

And Marry XMas! :)

**Comment by muammar** [comment]
@lzsolo nice!. I understand now, for mp3 audio files I have not implemented the `--input` flag. If you are having troubles streaming video files in mp4 format, try using the node backend by appending `--encoder-backend node`. 

Merry Christmas for you, too!.

**Comment by lzsolo** [comment]
@muammar 
Not working :(

zsolti@zsolti-Aspire-V3 ~ $ mkchromecast --input "/home/zsolti/MM.mp4" --video --port 5001 --encoder-backend node
Mkchromecast v0.3.8.1
Starting Video Cast Process...
Starting Node
Server running at http://0.0.0.0:5000/
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:5000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at net.js:1382:9
    at nextTickCallbackWith3Args (node.js:452:9)
    at process._tickCallback (node.js:358:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	Családi szoba
 
Casting to first device shown above!
Select devices by using the -s flag.
 
Családi szoba
 
 
Information about  Családi szoba
 
DeviceStatus(friendly_name='Családi szoba', model_name='Chromecast', manufacturer='Google Inc.', api_version=(1, 0), uuid=UUID('e601119c-4088-112b-10be-fd20797cbfbc'), cast_type='cast')
 
Status of device  Családi szoba
 
CastStatus(is_active_input=False, is_stand_by=True, volume_level=1.0, volume_muted=False, app_id='E8C28D3C', display_name='Backdrop', namespaces=['urn:x-cast:com.google.cast.debugoverlay', 'urn:x-cast:com.google.cast.cac', 'urn:x-cast:com.google.cast.sse'], session_id='d872b6be-2b2e-4cc2-ae1f-4ffa35d769e5', transport_id='d872b6be-2b2e-4cc2-ae1f-4ffa35d769e5', status_text='')
 
The IP of Családi szoba is: 192.168.1.72
Your local IP is: 192.168.1.69
 
The media type string used is: video/mp4
 
Cast media controller status
 
CastStatus(is_active_input=False, is_stand_by=True, volume_level=1.0, volume_muted=False, app_id='CC1AD845', display_name='Default Media Receiver', namespaces=['urn:x-cast:com.google.cast.debugoverlay', 'urn:x-cast:com.google.cast.broadcast', 'urn:x-cast:com.google.cast.media'], session_id='43d6d6e7-b666-463a-9ce6-ebdf17f1ea4f', transport_id='43d6d6e7-b666-463a-9ce6-ebdf17f1ea4f', status_text='Ready To Cast')
 
Remember to open pavucontrol and select the mkchromecast sink.

Ctrl-C to kill the Application at any Time

**Comment by muammar** [comment]
The problem there is because I haven't implemented the `port` for the node backend.

**Comment by mkhorton** [comment]
FYI, I just encountered this because shairport-sync uses 5000 as its default port, changing shairport-sync's port was easier since the current mkchromecast on apt doesn't yet have the --port flag.

I imagine there may be a few people using shairport-sync + mkchromecast to get Google Homes etc. to work with AirPlay, so this may be a common issue.

**Comment by lzsolo** [comment]
How do I change that shairport-sync's port?

**Comment by mkhorton** [comment]
If you install via apt on Debian (or Raspbian), there's a default config file installed (/etc/shairport-sync.conf), just uncomment the port line and change it to something else, such as 5001.

**Comment by lzsolo** [comment]
I don't use shairport-sync, I don't find this and shairport-sync.conf on my computer.

**Comment by muammar** [comment]
I will close this issue. Feel free to reopen it if needed.

**Comment by equivalent** [comment]
had the same issue `OSError: [Errno 98] Address already in use` then I've realized I'm connected to VPN. Disconnected from VPN worked for me
