### ISSUE TITLE
AVI file with media type video/x-msvideo

### ISSUE THREAD

**Issue by Aliuken** [muammar/mkchromecast#128]
I'm trying to cast a AVI file (with the media type video/x-msvideo) with mkchromecast but it doesn't work. I'm trying to use this command:
`
mkchromecast --video -i <filename>.avi`

However I can't see the video and in the command line I see:

> The media type string used is: video/mp4

Is there a way to specify the video media type in the command line? With youtube videos I have no problems.

**Comment by muammar** [comment]
@Aliuken I have pushed https://github.com/muammar/mkchromecast/commit/6126b738c02d128d4a3db85fc797a4941adc650a. Can you try it in the `devel` branch?.

**Comment by Aliuken** [comment]
I'm sorry. I don't know how to do that. I'm just a Linux beginner.
