### ISSUE TITLE
AttributeError: 'casting' object has no attribute 'cast' (cast.py line 310) when choosing a casting device

### ISSUE THREAD

**Issue by blackalegator** [muammar/mkchromecast#129]
Traceback (most recent call last):
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 310, in play_cast
    ' ' + self.cast.host)
AttributeError: 'casting' object has no attribute 'cast'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/mkchromecast/mkchromecast/tray_threading.py", line 105, in _play_cast_
    start.play_cast()
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 317, in play_cast
    if self.cast_to in _.player_name:
TypeError: 'in <string>' requires string as left operand, not SoCo

mkchromecast v0.3.8.1

Steps to reproduce
1. Lauch mkchromecast in a tray (python mkchromecast -t)
2. Search for devices
3. Pick a sonos device

**Comment by muammar** [comment]
Is it on Linux or macOS? I have tried on macOS with 676c8c64abc0e2fbed56b8ff7c5bcc94bbea9178 and it is working fine. I will try on Linux and will let you know.

**Comment by blackalegator** [comment]
Yes, its on linux. Sonos device.

**Comment by polyzen** [comment]
Is there just the one device? If not, this might be the error that occurs when trying to [cast with multiple Sonos devices available](https://github.com/muammar/mkchromecast/issues/125).

**Comment by blackalegator** [comment]
There are multiple Sonos devices available but I am choosing only one

**Comment by chappjc** [comment]
This error happens 90% of the time.  It's hard for me to even use mkchromecast now unfortunately.  Started doing this on my Arch linux system in maybe June or July.  If you keep starting mkchromecast over and over, eventually it works.

Running with something like:

    bin/mkchromecast --codec aac -b 240 -n Office

There are multiple Sonos devices, so I select one.  It doesn't seem to matter which one I select.

**Comment by muammar** [comment]
@chappjc thanks for your report. I think I have to contact Soco developers about this and see if they can shed some light about this problem. I just own one Sonos speaker and cannot reproduce this.

**Comment by LouBerry** [comment]
@muammar  any update on that topic? I am facing the same message.
