### ISSUE TITLE
No way to close the preferences pane in Ubuntu 16.10

### ISSUE THREAD

**Issue by xmbwd** [muammar/mkchromecast#13]
Using Ubuntu 16.10, the preferences pane, once opened, cannot be closed completely --- just minimized.  It remains in the launcher/dock (if using CairoDock).

**Comment by muammar** [comment]
I am installing Ubuntu 16.10 in a virtual machine to check this, because I don't use any desktop environment. I think I know what is causing the problem.

**Comment by muammar** [comment]
@xmbwd I have verified this. You are right. There is no button to close the window in unity. I will fix this for the next release. Thank you for reporting.
