### ISSUE TITLE
sudo apt-get install mkchromecast does not work

### ISSUE THREAD

**Issue by lamady** [muammar/mkchromecast#131]
I tried to install mkchromecast but it seems to be unavailable in my ubuntu distribution.
Also it is impossible to get cloned github being installed as PyQt5 is missing in any shape or form.
also installing it by sudo apt-get install PyQt5 fails as it is also missing.

**Comment by muammar** [comment]
https://github.com/muammar/mkchromecast#linux-4

**Comment by pandasauce** [comment]
See #151. It seems that you are on 16.04. This is a duplicate.
