### ISSUE TITLE
Unable to install mkchromecast_0.3.8.1-1_all.deb

### ISSUE THREAD

**Issue by akbagchi** [muammar/mkchromecast#133]
Hello Friends, 
I could not install the subjected file on my Ubuntu 16.04.3 LTS desktop. 
Please look at the screen shots, and help me. 
Wish you all a bright and happy new year 2018. 
:-)

![mkchromecast 3](https://user-images.githubusercontent.com/7348340/34453946-9300953e-ed85-11e7-9d99-dc4a81d11258.png)
![mkchromecast 2](https://user-images.githubusercontent.com/7348340/34453947-93397804-ed85-11e7-8ca6-7380439f8fda.png)
![mkchromecast 1](https://user-images.githubusercontent.com/7348340/34453948-9371107a-ed85-11e7-9326-08b2edcc45f8.png)

**Comment by muammar** [comment]
Ubuntu 16.04.3 is not supported. If you would like to use mkchromecast, I would suggest you to clone the repository and use it from "sources". Otherwise, you might try installing the dependencies by yourself using deb files available on Ubuntu 16.10.
