### ISSUE TITLE
Streamming for 1+ renders

### ISSUE THREAD

**Issue by Luisbona** [muammar/mkchromecast#141]
What I want to do is play simultaneously on an audio chromecast and a video chromecast. Unfortunately google does not support creating groups for "different" devices - that is, they do not guarantee compatibility between themselves !! .

It is also not possible to use pulse audio combine sink for network devices (ie, pulseaudio-dlna is not useful either).

Any way to get this functionality using mkchromecast?

**Comment by muammar** [comment]
See https://github.com/muammar/mkchromecast/commit/d1a3911b336e6a2cfe1af07c89dc2e0d1c543c1e.
