### ISSUE TITLE
App doesnt open correctly (OSX)

### ISSUE THREAD

**Issue by ThinkFar** [muammar/mkchromecast#143]
Hey,
I tried opening the app on my MacBook running 10.13.2 but it doesn't fully work. When I open activity monitor I can see the app running but nothing is showing in my menu bar. 

Have a good one and thanks for the help in advance,
Marcel.

**Comment by muammar** [comment]
I am using macOS 10.13.3. If the app is running, try to look for it on the menu bar, and change its colors in preferences. 

<img width="868" alt="screen shot 2018-01-30 at 18 47 22" src="https://user-images.githubusercontent.com/954209/35597826-36bde4e4-05ee-11e8-826b-b0520ed9460f.png">
<img width="354" alt="screen shot 2018-01-30 at 18 47 56" src="https://user-images.githubusercontent.com/954209/35597827-36c8d2c8-05ee-11e8-9958-57c89a846b29.png">

**Comment by ThinkFar** [comment]
It works with 0.3.7.1 but not with the new one.

**Comment by ThinkFar** [comment]
Ok, so I just tested the tool and it doesn't seem to transfer the audio. I can connect the program to the device but when I play audio it doesn't play it on the chromecast.

**Comment by ThinkFar** [comment]
And when I connect the tool to the chromecast, it just shows the cast icon with a black background. Dunno if that's intended that way.

**Comment by muammar** [comment]
@ThinkFar do you have soundflower installed? Can you send a picture about the black background?

**Comment by ThinkFar** [comment]
Yes, I have installed soundflower. I will send it to you as soon as possible :)

**Comment by ThinkFar** [comment]
https://www.canbike.org/public/images/062914/Chromecast_tab_casting_icon_on_tv.jpg
This is an image from google images but it's the same as I have. Just the Chromecast icon with a black background.

**Comment by ibizaman** [comment]
Wow, I thought I had this same issue but the icon is actually invisible with a black background. See the screenshots.

<img width="86" alt="image" src="https://user-images.githubusercontent.com/1044950/43937865-2b9a2d30-9c15-11e8-9b65-5044dc6b7658.png">

<img width="98" alt="image" src="https://user-images.githubusercontent.com/1044950/43937871-3732f8d4-9c15-11e8-8557-51b6affbb654.png">

**Comment by muammar** [comment]
Look at the preferences:

<img width="432" alt="screen shot 2018-08-09 at 23 51 13" src="https://user-images.githubusercontent.com/954209/43937986-2b74bfea-9c2f-11e8-86e8-3c749eac1c9c.png">
<img width="1280" alt="screen shot 2018-08-09 at 23 51 23" src="https://user-images.githubusercontent.com/954209/43937990-318aff2a-9c2f-11e8-9b46-0430763dc23a.png">

**Comment by ibizaman** [comment]
yesss thanks!
