### ISSUE TITLE
Basic Question? Does chrome casting require a Chromecast device or can any UPnP/DLNA device work?

### ISSUE THREAD

**Issue by phd21** [muammar/mkchromecast#144]
Hi muammar, and anyone else,

I have a basic Question? Does chrome casting require a Chromecast device or can any UPnP/DLNA device work?

Regards,
Phil
phd21

**Comment by muammar** [comment]
This application requires a chromecast or Sonos. There are other tools that let you cast to any UPnP/DLNA.
