### ISSUE TITLE
No Streaming Devices found

### ISSUE THREAD

**Issue by evgeniosme** [muammar/mkchromecast#145]
Hi,
i use Chromecast Ultra, Ubuntu 17.10, 64bit Pavilion laptop, xorg, mkchromecast 3.8 from .deb package and i get No Streaming Devices found. Chromium can't find the device either.
I can stream from Win 10 and  Chrome after disabling firewall. ufw says inactive. I did restart.

Thank you for your time

**Comment by evgeniosme** [comment]
A few restarts and it worked!
Thank you

**Comment by muammar** [comment]
Glad it is solved.
