### ISSUE TITLE
Should avoid transcoding if the files are already in a proper format

### ISSUE THREAD

**Issue by rbrito** [muammar/mkchromecast#150]
I just tried to cast something to my Android TV and even for supported formats (like a pure MP3 file that I encoded with LAME---BTW, I'm an upstream member of LAME here) the files are decoded, played with pulseaudio (or whatever) and reencoded and only then streamed.

This transcoding shouldn't happen if the files are in a supported format.

Thanks for creating this program, BTW.

**Comment by muammar** [comment]
You are right. The copy flag should be passed instead in ffmpeg. I will try to put something together.

**Comment by rbrito** [comment]
Hi, Muammar.

On Sun, Feb 11, 2018 at 2:55 PM, Muammar El Khatib
<notifications@github.com> wrote:
> You are right. The copy flag should be passed instead in ffmpeg. I will try
> to put something together.

Thanks. That will be awesome. Not only for audio, but (especially) for video.

It is "just" needed to discover the codecs (I guess that ffprobe can
help here), see if they are in the list of compatible codecs of a
chromecast and, if yes, just remux them (perhaps with fMP4)...

Of course, the devil is in the details, but that's a first
approximation. It also seems to be what VLC does in its new version:

    https://geoffreymetais.github.io/features/vlc-30/


Thanks,

Rogério Brito.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by polyzen** [comment]
@rbrito, why remux if they're compatible?

**Comment by muammar** [comment]
Yes, ffprobe will work with something like this:

```
ffprobe -show_format -show_streams -loglevel quiet -print_format json $filename
```
