### ISSUE TITLE
Stream to multiple devices at once

### ISSUE THREAD

**Issue by boredland** [muammar/mkchromecast#160]
Hi there!

I wanted to ask if its possible to stream to two devices at the same time (like a Chromecast Audio together with a Chromecast). If it is already possible I currently dont understand how I select the devices to stream to.

Yours
Boredland

**Comment by muammar** [comment]
HI! Yes, this I think it is possible. What has to be changed is the `cast` class to be multithreading or multiprocessing. I have to find some time to update this project faster. I will try my best but I cannot promise to be quick on that!

**Comment by boredland** [comment]
Sounds good. I put a little bounty on it :+1: 
https://www.bountysource.com/issues/56052601-stream-to-multiple-devices-at-once

**Comment by muammar** [comment]
Duplicated #141.

**Comment by muammar** [comment]
I think this is working, but for me, it does not do it very well. See https://github.com/muammar/mkchromecast/commit/d1a3911b336e6a2cfe1af07c89dc2e0d1c543c1e.

**Comment by muammar** [comment]
I will close this report, but feel free to reopen it :).
