### ISSUE TITLE
Youtube option - NameError: name 'platform' is not defined

### ISSUE THREAD

**Issue by norey** [muammar/mkchromecast#162]
```
[~]> mkchromecast -y https://www.youtube.com/watch?v=fc6ODCqepb8
Mkchromecast v0.3.8.1
The Youtube URL chosen: https://www.youtube.com/watch?v=fc6ODCqepb8
Playing video: fc6ODCqepb8
PID of main process: 2038
PID of streaming process: 2042
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	XBR-49X900E
 
Casting to first device shown above!
Select devices by using the -s flag.
 
XBR-49X900E
 
 
Information about  XBR-49X900E
 
DeviceStatus(friendly_name='XBR-49X900E', model_name='BRAVIA 4K GB', manufacturer='Sony', uuid=UUID('73d8250a-ad87-6aaa-2a7e-c38cc5e678b3'), cast_type='cast')
 
Status of device  XBR-49X900E
 
CastStatus(is_active_input=True, is_stand_by=False, volume_level=0.1111111119389534, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
The IP of XBR-49X900E is: 192.168.1.60
Your local IP is: 192.168.1.40
 
The media type string used is: audio/mp4
 
Cast media controller status
 
CastStatus(is_active_input=True, is_stand_by=False, volume_level=0.1111111119389534, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
Remember to open pavucontrol and select the mkchromecast sink.

Ctrl-C to kill the Application at any Time

[2018-03-19 12:36:27,749] ERROR in app: Exception on /stream [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/mkchromecast/mkchromecast/audio.py", line 748, in stream
    if (platform == 'Linux' and bool(backends_dict) is True and
NameError: name 'platform' is not defined
192.168.1.60 - - [19/Mar/2018 12:36:27] "GET /stream HTTP/1.1" 500 -
```
Am I missing something?

**Comment by muammar** [comment]
On Mon, Mar 19, 2018 at 1:41 PM, norey <notifications@github.com> wrote:

> [~]> mkchromecast -y https://www.youtube.com/watch?v=fc6ODCqepb8
>
>
> [2018-03-19 12:36:27,749] ERROR in app: Exception on /stream [GET]
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/share/mkchromecast/mkchromecast/audio.py", line 748, in stream
>     if (platform == 'Linux' and bool(backends_dict) is True and
> NameError: name 'platform' is not defined
> 192.168.1.60 - - [19/Mar/2018 12:36:27] "GET /stream HTTP/1.1" 500 -
>
> Am I missing something?
>
>
>
Can you try this?

mkchromecast --video -y https://www.youtube.com/watch?v=fc6ODCqepb8


The problem seems to be that the youtube video wants to be played by
the `audio` module that does not support that yet. I need to change
that or add support to it.


Best,

**Comment by norey** [comment]
Yep, that worked.

**Comment by muammar** [comment]
Thanks for the confirmation.

**Comment by muammar** [comment]
I fixed this. You can stream audio from youtube, too.
