### ISSUE TITLE
Stream desktop with audio

### ISSUE THREAD

**Issue by adombeck** [muammar/mkchromecast#164]
I can't get mkchromecast to stream the desktop video (using `--screencast`) and system audio at the same time. Is this not supported?

Btw, this is a really awesome application you created there! :)

**Comment by muammar** [comment]
It is supported: see https://github.com/muammar/mkchromecast/commit/d5f0884ed24730f11ee28bb449a3a702781a8e7f. You need the ` devel`  branch for this.

**Comment by pataquets** [comment]
@adombeck did you make to make it work?
Can the issue be closed?

**Comment by adombeck** [comment]
Yes, it works great!

**Comment by muammar** [comment]
> @adombeck did you make to make it work? Can the issue be closed?

Would you like helping with the development of the app?

**Comment by muammar** [comment]
@pataquets would you like to help with the development of the app?

**Comment by pataquets** [comment]
@muammar I don't have neither too much Python experience (just basic skills) nor available time, sorry. Thanks for the offering, thou. I just try to help a bit here and there as I come along.
However, I'd like to bring your attention to my suggestions at #398 and posting the project as 'co-maintainers' wanted. There seems to be some interest. Also, pinning the mentioned issue might be of some help. The issue might be useful in funnelling existing interest into action, keep an eye on it.
Just my 2c.
