### ISSUE TITLE
library files contains shebangs (they  should not).

### ISSUE THREAD

**Issue by leamas** [muammar/mkchromecast#171]
As heading says: The files in the mkchromecast directory contains shebangs like *#/usr/bin/env python*. This is plain wrong, they are not executed as stand-alone units.

The exception is mkchromecast.py. handled in #166 by moving to separate dir.

The shebangs looks innocent,  but causes packaging noise and should better be removed

EDIT: typos

**Comment by leamas** [comment]
A patch is available at https://paste.fedoraproject.org/paste/uXQZdie0CWRuvzY4-v9eDw

**Comment by muammar** [comment]
@leamas thanks!.
