### ISSUE TITLE
Bundled nodejs stuff breaks pypi install

### ISSUE THREAD

**Issue by leamas** [muammar/mkchromecast#176]
*python3 setup.py install* breaks on current devel. The culprit is the bundled stuff in nodejs/, in particular nodejs/bin/node (and the corresponding link in bin/).

nodejs/ state could by definition be restored using the  package-lock.json file. Also, bundling the MacOS node binary carries all sorts of risks, since it need to be maintained to handle at least security issues. 

Removing the nodejs stuff besides the toplevel nodejs/* regular files would decrease the size of the package drastically, an added bonus.

From my point of view, the solution here should remove nodejs/\*/\*, trusting npm to recreate the status from package-lock.json and adding a pointer to MacOS users how to install a properly maintained node binary. That said, I don't have the complete picture how this stuff is used.

EDIT: typos.

**Comment by leamas** [comment]
Adding a tentative compressed patch (compressed to make github accept it). It certainly needs a review.

[0001-nodejs-Nuke-bundled-stuff.patch.gz](https://github.com/muammar/mkchromecast/files/1881544/0001-nodejs-Nuke-bundled-stuff.patch.gz)

**Comment by leamas** [comment]
No... this was messy. The big, first patch does not apply since the node_modules stuff contains some non-utf8 stuff. So, my tentative proposal after downloading and uncompressing attached patch is instead:

     git rm -r nodejs/node_modules/
     git commit -am "nodejs: Remove generated node_modules directory (#176)."
     git rm -r nodejs/bin bin/node
     git commit -am "nodejs: Remove bundled MacOS binaries (#176)."
     git am  0001-nodejs-Generate-node_modules-instead-of-bundling-it.patch

[0001-nodejs-Generate-node_modules-instead-of-bundling-it.patch.gz](https://github.com/muammar/mkchromecast/files/1882549/0001-nodejs-Generate-node_modules-instead-of-bundling-it.patch.gz)

**Comment by muammar** [comment]
On Thu, Apr 5, 2018 at 11:08 PM, leamas <notifications@github.com> wrote:
>
> No... this was messy. The big, first patch does not apply since the node_modules stuff contains some non-utf8 stuff. So, my tentative proposal after downloading and uncompressing attached patch is instead:
>
>  git rm -r nodejs/node_modules/
>  git commit -am "nodejs: Remove generated node_modules directory (#176)."
>  git rm -r nodejs/bin bin/node
>  git commit -am "nodejs: Remove bundled MacOS binaries (#176)."
>  git am  0001-nodejs-Generate-node_modules-instead-of-bundling-it.patch
>
> 0001-nodejs-Generate-node_modules-instead-of-bundling-it.patch.gz
>
>


The only file that is important for both OS inside `nodejs` is
`html5-video-streamer.js`. The rest should be downloaded by using
package-lock.json as you mentioned.

**Comment by leamas** [comment]
> The only file that is important for both OS inside `nodejs` is `html5-video-streamer.js`

Right, I got that.  Still, this is a npm package, and as such is expected to have both a packaga.json and package-lock.json. So, IMHO it's   reasonable to add it (and it makes npm  happier).

> The rest should be downloaded by using package-lock.json as you mentioned.

Which means that we all agree upon removing node_modules form the repo?

What are your thoughts about the bundled MacOS binaries?

I might add that my perspective on this is heavily dictated by the packaging issues. My primary concern was to make this available in Fedora, but here is more too see from a packaging POV.

**Comment by leamas** [comment]
Fixed by PR #180
