### ISSUE TITLE
Linux Mint 18.3 - install from source - error pyqt5

### ISSUE THREAD

**Issue by ShinJii89** [muammar/mkchromecast#201]
Hi,
I have an error after `sudo pip install -r requirements.txt` everything seems to find fine except this:

Collecting PyQt5==5.9 (from -r requirements.txt (line 9))
  Could not find a version that satisfies the requirement PyQt5==5.9 (from -r requirements.txt (line 9)) (from versions: )
No matching distribution found for PyQt5==5.9 (from -r requirements.txt (line 9))

What to do?

**Comment by ShinJii89** [comment]
Hmmm I don't know how but I fixed this... but now last error... 

`Collecting gi==1.2 (from -r requirements.txt (line 10))
  Could not find a version that satisfies the requirement gi==1.2 (from -r requirements.txt (line 10)) (from versions: )
No matching distribution found for gi==1.2 (from -r requirements.txt (line 10))`

PyQT5 I fixed with `sudo pip3 install --user PyQT5` so I tried `sudo pip3 install --user gi` but nothing found...

**Comment by ShinJii89** [comment]
ANYONE?!?!?! I have installed `python-gi is already the newest version (3.20.0-0ubuntu1).` so wtf? Why it can't find this stupid thing in PIP INSTALL GI ?!?!

**Comment by muammar** [comment]
Try to install `python-pyqt5` package with `apt` instead of using `pip`.

**Comment by ShinJii89** [comment]
I have everything installed with apt.... pyqt5, gi etc. :/

**Comment by muammar** [comment]
Did you try to then execute the application? If you have already installed all dependencies shown in the  `requirements.txt ` file using `apt` you should be good to go.

**Comment by ShinJii89** [comment]
I have everytime error with GI package.... `Collecting gi==1.2 (from -r requirements.txt (line 10)) Could not find a version that satisfies the requirement gi==1.2 (from -r requirements.txt (line 10)) (from versions: ) No matching distribution found for gi==1.2 (from -r requirements.txt (line 10))`

**Comment by ShinJii89** [comment]
If I tried install .deb package I can't because I don't have pychromecast and I can't install it with apt -.-

**Comment by ShinJii89** [comment]
But with PIP it's installing pychromecast but not gi.... :/

**Comment by muammar** [comment]
That does not matter, don't pay attention to pip installation error. Try to execute mkchromecast and see if there is another module missing. If a module is missing, install it using `apt`. For pychromecast, I think it should be available via `apt`, too.

**Comment by ShinJii89** [comment]
But I don't have pychromecast via `apt` I don't know why... How to execute mkchromecast?

**Comment by muammar** [comment]
Oh, that is an issue. If you know what version of Ubuntu  your Linux mint is based off, then you can try to find pychromecast here https://packages.ubuntu.com/, download a version and install it with `dpkg -i`.

**Comment by ShinJii89** [comment]
It's based on Xenial but I searched pychromecast and there's nothing for xenial.....

**Comment by ljoli** [comment]
Hello,
I advice to you to upgrade linux Mint to 19 version.
It's on bionic version of UBUNTU.
https://blog.linuxmint.com/?p=3615

And you can find pychromecast  
https://packages.ubuntu.com/search?keywords=pychromecast&searchon=names&suite=all&section=all

**Comment by ShinJii89** [comment]
Yes but I have KDE VERSION and I can't update to 19........ :/

**Comment by ljoli** [comment]
Oooh ok It's pity :hushed:

**Comment by ShinJii89** [comment]
So I guess I can't do anything with that? Or maybe you have some older .deb package of mkchromecast for xenial or something??

**Comment by muammar** [comment]
Actually, if pychromecast is available for a newer version (maybe a release after xenial) that should work for you.

**Comment by ShinJii89** [comment]
https://packages.ubuntu.com/search?keywords=python-pychromecast I did this with artful (17.10) and after install mkchromecast (0.3.7)  it opens and then if I try click "search for media devices" it close itself.... :(

**Comment by muammar** [comment]
Can you paste the backtrace error you get, please?

**Comment by ShinJii89** [comment]
I uninstalled everything because I lost 2 days for it and it made me angry :D so I stayed with google chrome extension....

**Comment by muammar** [comment]
Sorry to hear that. I totally get you. Thanks for reporting anyway. I am closing this report for now.
