### ISSUE TITLE
gi package removed

### ISSUE THREAD

**Issue by aaronkurtz** [muammar/mkchromecast#206]
```
Collecting gi==1.2 (from -r requirements.txt (line 10))
  Could not find a version that satisfies the requirement gi==1.2 (from -r requirements.txt (line 10)) (from versions: )
No matching distribution found for gi==1.2 (from -r requirements.txt (line 10))

```

It looks like gi was removed from pypi.

**Comment by eastein** [comment]
I have this issue too, with python 3.5.2 on Ubuntu 16.04 LTS. Based on some Googling, gi is PyGObject. I have other problems trying to use mkchromecast though so I don't know if this is accurate or helps.

**Comment by muammar** [comment]
Sorry for the late reply, I have updated the `requirements.txt` file. Does it work now?

**Comment by muammar** [comment]
I think this should be fixed after updating requirements.txt. Note that Python2 support was drop.
