### ISSUE TITLE
Error with Ubuntu 16.04 and tray option

### ISSUE THREAD

**Issue by eduardoxy** [muammar/mkchromecast#208]
Hello friend,

I am trying to install your software in my Ubuntu 16.04 x64.
I can install it from the sources and run via terminal succesfully.
But when I try to run "mkchromecast -t" I get the following error:

Traceback (most recent call last):
  File "./mkchromecast", line 15, in <module>
    from mkchromecast.cast import casting
  File "./../mkchromecast/cast.py", line 8, in <module>
    from mkchromecast.preferences import ConfigSectionMap
  File "./../mkchromecast/preferences.py", line 60, in <module>
    from PyQt5.QtWidgets import (QWidget, QLabel, QComboBox, QApplication,
ImportError: /home/eduardoxy/.local/lib/python3.5/site-packages/PyQt5/QtCore.so: undefined symbol: PySlice_AdjustIndices

Could you have some solution to that problem?
ps: I have installed the pyqt5, but I'm not able to identify what is wrong.

Thank you!

**Comment by eduardoxy** [comment]
Hello!

I have corrected the error I will write the solution here.
I've found this [bug on PyQt](https://www.riverbankcomputing.com/pipermail/pyqt/2018-July/040511.html). In order to correct it, I install the python 3.6.6 from the binaries following [this] (https://tecadmin.net/install-python-3-6-ubuntu-linuxmint/) simple tutorial.

So then I have followed the tips on #151 in [this comment] (comment) and build a virtual environment for python3.6, activate it and install the mkchromecast using the "pip install -r requirements.txt".

After those steps, the command is running with the -t option like a charm.
Thank you.

**Comment by muammar** [comment]
Thank you for writing this. I am sorry I am not very responsive.

**Comment by muammar** [comment]
I added this to the Wiki. Closing this issue.

**Comment by eduardoxy** [comment]
Perfect!

Best regards
