### ISSUE TITLE
Can cast to Google Home and Chromecast, but does not find my Sonos 3

### ISSUE THREAD

**Issue by datasmithy** [muammar/mkchromecast#209]
I am using mkchromcast 0.3.8.1, on Ubuntu 18.04.1, installed using the .deb package.  

I can find and cast to Google Home and Chromecast, and this works great, but it can't find my Sonos 3 player.

I am assuming the soco python package comes as a dependency on the .deb package.  If it does not, it probably should.

**Comment by muammar** [comment]
Soco is not yet available in Debian. You can do a pip3 install --user soco to activate the Sonos support.

**Comment by muammar** [comment]
Were you able to solve this problem? I can cast from my Linux/macOS to Sonos with no problem.

**Comment by smancke** [comment]
I'm also not able to find my sonos device (play 5). I have tested with the current master and the latest release 0.3.8.1:

```
$> python3 start_tray.py 
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
Configuration file exists
Using defaults set there
Configuration file exists
Using defaults set there
No devices found!
Cleaning up /tmp/...
[Done]
Killed
```

When I install the command line client of soco (socos), I can find my box and is able to control it.
Any idea, what can I do to debug it further?

**Comment by muammar** [comment]
Yes, try this instead (assuming you are using the `master` branch):

```
bin/mkchromecast -t
```

Let me know if that works for you. thanks.

**Comment by smancke** [comment]
Same result: No device found.

```
./bin/mkchromecast -t
Mkchromecast v0.3.9
Selected backend: /usr/bin/parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
Configuration file exists
Using defaults set there
Configuration file exists
Using defaults set there
:::Tray::: No devices found!
availablecc received
```

**Comment by muammar** [comment]
@smancke did you install the soco module? `pip install soco`.

**Comment by smancke** [comment]
Solved: I had installed soco with pip, which downloaded in the python2.x environment, but started mkchromecast with python3. after installing soco with pip3 it worked.

**Comment by muammar** [comment]
@smancke nice! enjoy!
