### ISSUE TITLE
Make PyChromecast an optional dependency

### ISSUE THREAD

**Issue by polyzen** [muammar/mkchromecast#211]
I know this is Mk*chromecast* and all, but considering this can be used to cast solely to Sonos devices, it would be nice to not require PyChromecast be installed.

PS: This would also free me from maintaining a dependency I can't test :p.

**Comment by muammar** [comment]
That sounds good. Let me go ahead that today I have some free time.

**Comment by muammar** [comment]
@polyzen can you try this thing now? I pushed a change that at least is working on my computer.

**Comment by polyzen** [comment]
Works great, thank you for handling this so quickly.

**Comment by polyzen** [comment]
The tray icon now also works for me (applied this patch directly to the latest release), although I don't really know if it's because of this commit.

**Comment by muammar** [comment]
Do you mean the system tray in KDE?

**Comment by polyzen** [comment]
On October 13, 2018 10:43:28 PM EDT, Muammar El Khatib <notifications@github.com> wrote:
>Do you mean the system tray in KDE?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/muammar/mkchromecast/issues/211#issuecomment-429591679

Mkchromecast's tray icon, in i3wm.

-- 
Best,
polyzen

**Comment by polyzen** [comment]
Actually I may have confused my tray icon issues with razercfg's applet.
