### ISSUE TITLE
Unable to cast on Ubuntu 18.10

### ISSUE THREAD

**Issue by pwd-github** [muammar/mkchromecast#213]
I can launch the app, select the device, but for some reason, the sound still comes out through the laptop. This is via the GUI and CLI.

**Comment by muammar** [comment]
On Thu, Oct 25, 2018 at 8:12 AM Paul <notifications@github.com> wrote:

> I can launch the app, select the device, but for some reason, the sound
> still comes out through the laptop. This is via the GUI and CLI.
>
>
>
Did you open pavucontrol and selected Mkchromecast?

https://raw.githubusercontent.com/muammar/mkchromecast/master/images/mkchromecast_linux.gif



-- 
Muammar El Khatib.
http://muammar.me

**Comment by pwd-github** [comment]
I'm going to say PLBCAK as mkchromecast has been working fine for the past three days. My apologies.

**Comment by muammar** [comment]
@pwd-github that is fine. I am glad everything worked out.
