### ISSUE TITLE
[question] Does the Google Chrome Browser already do what mkchromecast does?

### ISSUE THREAD

**Issue by vahidpaz** [muammar/mkchromecast#220]
I haven't actually done any casting to a Chromecast yet, but I did notice something:

The Chrome browser on Linux has a dropdown that allows you to cast either: (1) video/audio file, or (2) desktop, or (3) tab. See attached image. Does option 1 here do the same thing as mkchromecast? What features do mkchromecast offer that the chrome browser doesn't?

I found this  by reading: https://support.google.com/chromecast/answer/3228332#

Thanks for any clarification.

![chromecast](https://user-images.githubusercontent.com/3666249/48868379-38453a00-ed8e-11e8-97fd-bb62fa4575c9.png)

**Comment by vahidpaz** [comment]
Thanks for the info. I'm going to get a chromecast ultra this next week so I can play with mkchromecast as well as the chrome browser to better understand the differences.

**Comment by vahidpaz** [comment]
Well I bought a Chromecast Ultra and can give you an update. I use Linux also.

Unfortunately the only HDMI media receiver I have right now is a monitor without speakers. I know mkchromecast's key feature is audio so I can't make any comments there. I did, however, play with the Google Chrome browser as a casting source. I was able to select the "Cast file" option and choose an mp4 -- it played on my chromecast monitor just fine. It wasn't casting my browser tab nor my desktop (there was no mouse, etc). I could also "Cast file" and select an mp3, which I presume was playing fine ;-)

I can also cast my entire linux desktop by choosing "Cast desktop," effectively making a mirror of my laptop's screen. While casting the desktop I played a movie using vlc on linux, which obviously displayed on chromecast without issues.

Google Chrome doesn't make the audio output device (sink) that mkchromecast does. I can understand some of the differences between these two pieces of software. I'm curious if Chrome's "Cast desktop" also casts audio. If it does then functionally it would have all the features of mkchromecast, right? Albeit the quality level might be different?

Maybe you can tell me if the Cast Desktop has audio. If it doesn't then I can see the gap that mkchromecast fills.

Cheers.

**Comment by vahidpaz** [comment]
I found some speakers and I'll answer my own question: **chrome browser's "cast desktop" does not support audio**. Only video is cast. The audio still plays through the computer's speakers while the video can also be seen on the chromecast receiver.

Now I understand why we have mkchromecast. Thanks again.

**Comment by muammar** [comment]
Thanks for your interest! I am sorry I could not reply to you earlier. This is just to add that Mkchromecast can also stream video! 

Best.

**Comment by polyzen** [comment]
> What features do mkchromecast offer that the chrome browser doesn't?
- Sonos support
- Much more lightweight. Some people use other browsers, and wouldn't want to install Chrome/Chromium

BTW from the Chromecast Help link you posted:
```
Cast videos and media

    On the video or media you're watching, click Cast Cast.
    You'll see the video or images on your computer and TV, but you’ll only hear sound on your TV. Sounds for other tabs and apps will still play on your computer.
```
