### ISSUE TITLE
Very long delay (>30secs) on macOS Sierra 10.12.6

### ISSUE THREAD

**Issue by rossco255** [muammar/mkchromecast#221]
Hello! Very glad to find this app, the lack of Chromecast connectivity on both Spotify and iTunes is maddening.

I installed using homebrew, and the functionality is all there, but there's a latency of over 30 seconds between the computer and the Chromecast. I use Soundflower regularly without any such problems. Is this the sort of thing that switching to ffmpeg rather than node might help?

**Comment by polyzen** [comment]
Sure is. IIRC the `wav` format doesn't work yet on macOS, but that would reduce latency even more.

**Comment by rossco255** [comment]
Wav is just noise. Flac however has the delay down to a much more manageable 8 seconds.

**Comment by diegotrigo** [comment]
> I think I got 8 seconds with `mp3` at `320 kbps` as well.

What about sample rate?

**Comment by polyzen** [comment]
The default, `44100`.

**Comment by pasikarkkainen** [comment]
8 seconds is still a very long delay. Which setting needs to be tweaked to get it to something tolerable, like less than one second?

**Comment by vojczejk** [comment]
Experiencing same behavior on Debian 9, mkchromecast v0.3.7.

**Comment by pasikarkkainen** [comment]
@muammar Any idea what's the reason for the huge delay? Is there some big audio buffer in use?

I guess I need to start reading the sources to figure it out..

**Comment by muammar** [comment]
On Sat, Feb 9, 2019 at 2:43 PM pasikarkkainen <notifications@github.com>
wrote:

> @muammar <https://github.com/muammar> Any idea what's the reason for the
> huge delay? Is there some big audio buffer in use?
>
> I guess I need to start reading the sources to figure it out..
>

No idea. I tried before to fix it but never succeeded. This does not happen
to me when I use Sonos speakers. I don't know what the difference is.

**Comment by polyzen** [comment]
Sonos here as well.

**Comment by pasikarkkainen** [comment]
@polyzen hmm, so you have ~8 seconds delay with Sonos, but @muammar doesn't.. how much is your delay/latency, @muammar ?

**Comment by polyzen** [comment]
Apparently the `node` backend on macOS has <2s delay, but according to [this comment](https://github.com/muammar/mkchromecast/issues/61#issuecomment-305978056), it should also be possible with `ffmpeg`?

**Comment by muammar** [comment]
This is with ffmpeg in macOS. I am casting to my sonos speakers using aac with 500k. 

https://photos.google.com/share/AF1QipPb0Fn2IdBxKtlW9hk0_7GpuSdHuk4P_L67qKtWWodYjrh6crBOChY_YRksmU8tPg?key=VkdkWUxhRV9ROUIxTkNVcHNwVGU4Wl9QNlV6RHlR

The video SUCKS but shows the idea :).

**Comment by legolasdimir** [comment]
I am seeing the same delay on xubuntu 18.04 LTS I am very new to this. Has anyone found any settings that can be tweaked to reduce or eliminate the delay?

**Comment by viktorsmari** [comment]
I also have around ~30s delay on Ubuntu Studio (16.04, 18.10) when casting to Chromecast Audio.

**Comment by muammar** [comment]
If some of you are interested, please check out this https://github.com/muammar/mkchromecast/commit/b6d0b3be4ba1cc54d936a591a5181ad9c7093ac6.

**Comment by viktorsmari** [comment]
> If some of you are interested, please check out this [b6d0b3b](https://github.com/muammar/mkchromecast/commit/b6d0b3be4ba1cc54d936a591a5181ad9c7093ac6).

If I want to test it on Linux, I need to build it right?
Are there build instructions in the docs somewhere? I cannot find it

**Comment by muammar** [comment]
> > If some of you are interested, please check out this [b6d0b3b](https://github.com/muammar/mkchromecast/commit/b6d0b3be4ba1cc54d936a591a5181ad9c7093ac6).
> 
> If I want to test it on Linux, I need to build it right?
> Are there build instructions in the docs somewhere? I cannot find it
> 
> EDIT:
> In the `setup.py` I found this:
> `python3 setup.py build`
> `python3 setup.py install`
> Which created a new `bin/mkchromecast` - which I use to run the program.
> 
> And now the delay is 24 seconds
> 
> Am I missing a step?

The easiest way would be to clone the repo (I think you already did that), and inside it do `bin/mkchromecast --yourflagshere`.

**Comment by viktorsmari** [comment]
But would that use the latest commit?
I pulled from the git repo and the `bin/mkchromecast` files timestamp was still ~ 3 weeks old.

So how can I **use** the latest commit?

**Comment by muammar** [comment]
> But would that use the latest commit?
> I pulled from the git repo and the `bin/mkchromecast` file's timestamp was still +3 weeks old, so I guess the binary was not updated even though the repo has new commits.
> 
> So how can I **use** the latest commit?

`bin/mkchromecast` is just a python script. If you use it, it will load the updated modules that I changed in the last commit.

**Comment by muammar** [comment]
I forgot to mention that before executing the application you have to verify that you are in the latest commit with `git pull`.

**Comment by viktorsmari** [comment]
Thanks for clarifying. On Ubuntu 19 the delay is still long, around 25 seconds.

**Comment by jphein** [comment]
mkchromecast v0.3.8.1
I am getting a 30 second delay on Ubuntu 19.10.

**Comment by b00n12** [comment]
Debian 9, regardless of the mkchromecast configuration (codec, backend, etc) and version (tested 0.3.9, 0.3.8, and 0.3.7) and regardless weather using alsa or pule delays of at least 20 seconds.

**Comment by sillydan1** [comment]
Debian 10, I will always get around 30-38 seconds of delay. The very first time I ran mkchromecast I got 27 seconds, but that's probably just a fluke

**Comment by muammar** [comment]
I think this helps: https://github.com/muammar/mkchromecast/commit/30f4e85bf1220ea5534748adf65f77b35c1b255e I will close this report but feel free to reopen.
