### ISSUE TITLE
Cast mp3 files

### ISSUE THREAD

**Issue by filcap76** [muammar/mkchromecast#229]
Hello,
I am trying to use mkchromecast to enable Google Home (through vocal activation) to play the music stored on my local NAS.

MY PLAN:
I will soon buy a QNAP TS-251A NAS that can run a Virtual Machine.
I have an idea to create a Linux Virtual Machine to run on my QNAP NAS, and then create and deploy a web service that executes locally, from the command line, mkchromecast command to cast music files (stored on the NAS) to a target that can be a Google Home device. 
Then I will create an IFTTT recipe triggered by a specific sentence ("Hey Google, Play my Rock playlist") that using a Webhook will make a web request to invoke the aforementioned web service.

MY CURRENT STATUS:
I've created a Debian 9 Virtual Machine and I have installed mkchromecast (v.0.3.7) and mkchromecast-pulseaudio.
`mkchromecast -d` correctly identifies my Google Home device.
If I run `mkchromecast -n "My Google Home Mini"` the command succeeds and I can hear a "beep" on the device.
If I start playing an mp3 on the Virtual Machine and I launch `pavucontrol` I don't find the mkchromecast sink (as I was expecting instead), but if I select `NULL OUTPUT` I can correctly hear the music from my Google Home device!  

MY PROBLEMS:
For my purposes I have three main problems:

- I need that everything works automatically; I have to avoid the manual selection of the sink on pavucontrol...
(Maybe using ALSA would help, but I need some more details to configure it...) 

- I am not able to get working the cast of an mp3 file with the command `mkchromecast -i "/home/osboxes/Music/song.mp3" -n "My Google Home"`; (the music does not start and I can't even configure the sink on pavucontrol)

- Finally I would need to cast a playlist or, at least, all the files in a folder.

I would appreciate any advice to solve my problems.
Thank you very much in advance!
   Filippo

**Comment by filcap76** [comment]
I'm trying with ALSA; in debug mode I can see that something is correctly streamed out to the right target, but I can't hear any music on the Google Home (I just hear the "beep" when the connection is established).

**Comment by filcap76** [comment]
Hi Muammar! 
Thanks for your reply, but I'm missing the relationship with #230. 
I'm trying to cast a specific audio file (or a list of files) and not the full audio played on the machine. The cast should stop (and the process terminate) when that file (or list of files) has been played. 
I think I have understood that the "-i" option is supposed to do right that. Am I missing anything? 
   Thanks! 
 Have a wonderful end of the year! 
     F.

**Comment by muammar** [comment]
About delay: see https://github.com/muammar/mkchromecast/issues/292.
