### ISSUE TITLE
Can't set desired bit depth except 32 in asoundrc 

### ISSUE THREAD

**Issue by ao-il** [muammar/mkchromecast#23]
ALSA won't set any bit depth except 32 in hwparams which results in resampling my 16 bit ogg files. Thanks in advance!

**Comment by muammar** [comment]
For the moments I have no idea how to change `asoundrc` so that the bit depth is 16 bits. I will get back to you with this soon. If you get to find the answer, please do not hesitate to write it here!.

**Comment by ao-il** [comment]
You set bit depth with..
format S16_LE
But it refuses anything but 32.

**Comment by ao-il** [comment]
No. I think I no longer have use for it, but thanks for asking. BTW, the
latency is a lot better with wav. Could it be the compression that causes
the delay?

**Comment by muammar** [comment]
@ao-il  yes, I have the same hypothesis :). When I want less delay I use wav or flac. When I have a bit more of time I will use other webserver different from python Flask (maybe node?). 

Is it fine to close this?.

**Comment by ao-il** [comment]
Yes, it's fine.

**Comment by muammar** [comment]
Thanks.
