### ISSUE TITLE
Ubuntu Studio 18.10 install fails on PyQt5

### ISSUE THREAD

**Issue by viktorsmari** [muammar/mkchromecast#239]
After cloning the repo and running: `pip install -r requirements.txt`

> Could not find a version that satisfies the requirement PyQt5==5.11.2 (from -r requirements.txt (line 5)) (from versions: )

I also tried using `virtualenv` and `pipenv` which also fail with the same error.

**Comment by muammar** [comment]
You can install it with apt:

```sudo apt install python3-pyqt5```. 

Sometimes the installation of PyQt5 with pip fails.

**Comment by viktorsmari** [comment]
This is what I had to do on Ubuntu Studio 19.04 system after cloning the repo:

`sudo apt-get install -y python3-dev python3-pip python3-pyqt5 `

Inside the mkchromecast cloned folder:
`python3 -m pip install -r requirements.txt`

Now I can run:
`python3 bin/mkchromecast`
