### ISSUE TITLE
Change documentation for `git clone ... --depth 1`

### ISSUE THREAD

**Issue by UgoTurner** [muammar/mkchromecast#240]
Hey !

First of all, thanks for this project !
It's not a big deal but I have noticed that the repo history is a little bit "heavy" (~325 MiB) and when you just want to build the project from source you just need the lastest version of master (~13 MiB). 
So maybe the documentation could be updated :

~git clone https://github.com/muammar/mkchromecast.git~
git clone https://github.com/muammar/mkchromecast.git --depth 1

**Comment by muammar** [comment]
Done. Good recommendation.
