### ISSUE TITLE
A few queries

### ISSUE THREAD

**Issue by mattomatto** [muammar/mkchromecast#25]
Hi muammar, 

I had a couple of questions about mkchromecast and wasn't sure where else to post them, hope you don't mind me doing it here.

1 - I'm having trouble launching mkchromecast on startup.  I've tried a variety of methods including a 'post-up' bash script, a rc.local command, and a cron command.  Each time, the chromecast connects, but the audio sink is not created.  I'm sure it's not a problem with pulseaudio, because if I do it manually, it always works fine. Do you know a method that has been proven to work?

2 - Is there a way of testing if mkchromecast is still connected to a chromecast and re-connecting if it is not? I eventually want my system to be able to automatically re-connect to available chrome casts after they have been 'hijacked' and become available again.

Thanks for your time!

**Comment by muammar** [comment]
@mattomatto 

> I had a couple of questions about mkchromecast and wasn't sure where else to post them, hope you don't mind me doing it here.
> 

It is fine to post it here. 

> 1 - I'm having trouble launching mkchromecast on startup. I've tried a variety of methods including a 'post-up' bash script, a rc.local command, and a cron command. Each time, the chromecast connects, but the audio sink is not created. I'm sure it's not a problem with pulseaudio, because if I do it manually, it always works fine. Do you know a method that has been proven to work?
> 

For the moments I do not know a method that works for that user case. I think it would be good to find a solution. If you get a solution before me, do not hesitate to post it here. 

> 2 - Is there a way of testing if mkchromecast is still connected to a chromecast and re-connecting if it is not? I eventually want my system to be able to automatically re-connect to available chrome casts after they have been 'hijacked' and become available again.
> 

This is feasible. I will add a new flag that creates either a process or thread to monitor if the chromecast is connected otherwise it will rereconnect automatically. It sounds as very good idea. 

> Thanks for your time!

Thanks for your interested in this app. 

Cheers.

**Comment by mattomatto** [comment]
> For the moments I do not know a method that works for that user case. I think it would be good to find a solution. If you get a solution before me, do not hesitate to post it here.

I  think I've found a stable solution - the key is to make sure pulseaudio is run by the user after log in, and that mkchromecast is also run by the user after login (i.e, not sudo).  I did this by putting this script: 

```
sleep 10
	#! /bin/sh
	pulseaudio –D
	cd mkchromecast
	python3 /home/pi/mkchromecast/mkchromecast.py

```
in /home/pi/scripts/launch.sh

and then adding 

`@lxterminal --command “/home/pi/scripts/launch.sh”`

to the end of /home/pi/.config/lxsession/LXDE-pi/autostart


> This is feasible. I will add a new flag that creates either a process or thread to monitor if the chromecast is connected otherwise it will rereconnect automatically. It sounds as very good idea.

That's great to hear it would be possible.  What I'm trying to achieve is using the raspberry pi to act as house radio, streaming to all chromecasts.  If I choose to hijack one of the chromecasts to stream something from my phone, it would be great if mkchromecast would allow it, then wait until that chromecast becomes available again, and re-connects to it, to restore the 'house radio'.

All working so far except this potential feature! :D

**Comment by muammar** [comment]
> I think I've found a stable solution - the key is to make sure pulseaudio is run by the user after log in, and that mkchromecast is also run by the user after login (i.e, not sudo). I did this by putting this script:

Thank for the information, I think I will add it to the wiki.

> That's great to hear it would be possible. What I'm trying to achieve is using the raspberry pi to act as house radio, streaming to all chromecasts. If I choose to hijack one of the chromecasts to stream something from my phone, it would be great if mkchromecast would allow it, then wait until that chromecast becomes available again, and re-connects to it, to restore the 'house radio'.

Interesting user case. I have just recently moved, and I hope to add this functionality soon. Glad to know that, except for this, everything works. 

Cheers,

**Comment by danikei** [comment]
This is such a great idea, I haven't gotten to try mkchromecast yet this but I might get a pi + chromecasts to do as mattomatto said. I was just looking around linux casting solutions and this seems by far the most well put together, thanks muammar! I'll keep an eye on the project 👍 :)

**Comment by muammar** [comment]
@danikei thank for your message. I am working on the reconnecting option. I hope to release it by the end of this month. Cheers.

**Comment by muammar** [comment]
Dear @mattomatto and @danikei. I think I have implemented the `--reconnect` flag. Could you test if it is working?. It is available in the `devel` branch. If it is fine, I can proceed to close this report and do a new release this week. Thanks :).

**Comment by danikei** [comment]
Awesome @muammar , I'll try it later this week! (I'm out for xmas, happy holidays, btw!)
A bit off-topic:
I was working on an almost-headless pi project that gets both analog audio (vinyl turntable) + airplay (for apple products) to mkchromecast (via alsa) so it can cast it to chromecasts around the house and if --reconnect works it will be perfect. I got it working so far in a mostly rough and non optimised way, since my knowledge in linux is very limited. 
Right now I wanted to add a big heatsink to my pi3, since it gets very very hot (ubuntu+shairport+arecord+mkchromecast), and a shutdown button... But I was thinking in making in the future a post of how I did it for anyone who wanted to do something similar and also to try to get a bit of help making it better (truly headless and less cpu intensive): do you or @mattomatto know where (maybe a reddit sub? blog post?) I could do this, where other people could be interested? 
And again, thanks muammar, your project got me to tinker around -after many many years- with linux and a reason to get into a pi project -which I always wanted to try but didn't have a real reason to.

**Comment by danikei** [comment]
So I finally got to try it, and it works! Congrats @muammar 
In my opinion it actually works a bit too well, haha. Could it be possible to give --reconnect like a timer before it checks if it lost connection? like --reconnect 5 for five minutes or something like that.
Now what happens is that mkchromecast reconnects instantly the moment another thing tries to use the chromecast. So, for example, if mkchromecast is casting with --reconnect but I want to cast for a bit something else (say, for example, I just want to put a song from a phone but have the original mkchromecast back in a bit) the moment it loses connection to the new cast, mkchromecast reconnects again -making impossible to cast anything else.
Not sure if I made myself clear or if its even possible (or somebody else thinks it would be useful).
On the plus side, I tried it with a chromecast tv (I only had a chromecast audio before) and was pleased to see that it also works.

**Comment by muammar** [comment]
> So I finally got to try it, and it works! Congrats @muammar
In my opinion it actually works a bit too well, haha. Could it be possible to give --reconnect like a timer before it checks if it lost connection? like --reconnect 5 for five minutes or something like that.

Yes, it is totally possible. I am going to do it. I had noted it in the code: https://github.com/muammar/mkchromecast/blob/master/mkchromecast/cast.py#L407 For the moments, you can hard-code the 5 seconds in the line shown above. I will make the `--reconnect` flag to accept integers representing seconds. 

>Now what happens is that mkchromecast reconnects instantly the moment another thing tries to use the chromecast. So, for example, if mkchromecast is casting with --reconnect but I want to cast for a bit something else (say, for example, I just want to put a song from a phone but have the original mkchromecast back in a bit) the moment it loses connection to the new cast, mkchromecast reconnects again -making it impossible to cast anything else.

Yes, what I implemented was a simple (and violent) reconnection. What you want is something like an `observer` that watches if the chromecast is not idle and if it is, then it will connect to it. Is it right?.

>Not sure if I made myself clear or if its even possible (or somebody else thinks it would be useful).
On the plus side, I tried it with a chromecast tv (I only had a chromecast audio before) and was pleased to see that it also works.

Yes, this app works well for the chromecast tv and it can also stream video btw.

**Comment by mattomatto** [comment]
Thanks a lot for implementing this!  I'm not able to test at the moment,  but sounds like it works great.   My main reason for using mkchromecast was to stream from the raspberry pi to chromecast using my phone as a remote. I have since found out that chromecast actually connect to a stream directly and so the pi was just complicating things..  But for local streaming stuff this would still be a perfect feature addition to steal back chromecast if they have been lost or hijacked :)

**Comment by muammar** [comment]
On Thu, Jan 05, 2017 at 12:17:23PM -0800, mattomatto wrote:
> Thanks a lot for implementing this! I'm not able to test at the moment, but
> sounds like it works great. My main reason for using mkchromecast was to stream
> from the raspberry pi to chromecast using my phone as a remote. I have since
> found out that chromecast actually connect to a stream directly and so the pi
> was just complicating things.. But for local streaming stuff this would still
> be a perfect feature addition to steal back chromecast if they have been lost
> or hijacked :)


That's correct. Thanks for your message.

--
Muammar El Khatib.
http://muammar.me | http://proyectociencia.org

**Comment by azertybepo** [comment]
Hello, I'm trying to play some mp3 files **remotely** from a website (tts files otf  for my home automation project), I'm using your excellent app **headlessly** like that : python3 /usr/share/mkchromecast/mkchromecast.py **--source-url** http://xxx.xxx.xxx.xxx/xxx.mp3. It is working but the connection delay to the chromecast is defeating the purpose.
So I was wondering if it was possible to **keep the connection alive**  without playing anything (like mkchromecast.py without arg) then when needed, just play the source-url. (incidentaly making use of the -hijack, thus my post on this thread)
