### ISSUE TITLE
How does this work with spotify?

### ISSUE THREAD

**Issue by nickcorona** [muammar/mkchromecast#253]
After installation of mkchromecast, I open Spotify desktop client for Linux, and my Chromecast devices are still unrecognized.

**Comment by IWantOriginalName** [comment]
You wanna open pulseaudio and change build-in audio on mkchromecast.

**Comment by viktorsmari** [comment]
I open `pavucontrol`, click Playback tab, and select Mkchromecast for Spotify:

![2019-08-01_10-08-29](https://user-images.githubusercontent.com/1689020/62276450-5c403b80-b444-11e9-96c1-a43e40a90e14.png)

**Comment by smalchow** [comment]
Hi, if you are looking at something from the CLI and with spotify connect, i wrote something for openhab, but it works from any spotify connect device

**Comment by muammar** [comment]
Delay issue being treated here: https://github.com/muammar/mkchromecast/issues/292
