### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'lame': 'lame'

### ISSUE THREAD

**Issue by axj336** [muammar/mkchromecast#258]
When installing from source on 16.04 I got this error. It can be fixed by installing lame (`sudo apt-get install lame`).

Previous install instructions were to pull the repo, install the dependencies (`sudo apt-get install lame ffmpeg`, then `pip install -r requirements.txt`) install the app `pip install -e .`. The pychromecast dependancy referenced in #151 is fixed when installing the dependencies in this way. 

I would recommend changing line 759 of `audio.py` to read something like
```python
        try:
        	process = Popen(command, stdin=parec.stdout, stdout=PIPE, bufsize=-1)
        except FileNotFoundError:
        	print('Failed to execute:')
        	print(command)
        	print('Have you installed lame, see github.com/muammar...?')
        	raise
```
before closing the issue to make debugging easier :). 

(I know it does say in the install instructions to install lame, but I missed that line and it took me  a while to debug).

**Comment by muammar** [comment]
Would you prepare a PR? I would be glad to accept this change.

**Comment by axj336** [comment]
Nice! :)
