### ISSUE TITLE
Seek not working

### ISSUE THREAD

**Issue by iodigitalsec** [muammar/mkchromecast#259]
In the current latest version v0.3.9, seek isn't working. 

When you execute: mkchromecast --video -i video.mp4 --seek 00:23:00, the resulting ffmpeg command does not contain the '-ss 00:23:00' flag. 

Edit video.py and move the 'if seek is not None' back 4 spaces to the parent 'if' - then it works. I would do a PR but I might be introducing additional bugs as I couldn't get my head round the large if/elif/else nested blocks

**Comment by Silent-Hunter** [comment]
This doesn't work for me either. I can try making the change you mentioned and hopefully that won't introduce bugs.

**Comment by iodigitalsec** [comment]
I have fixed this and this is now merged into master.

**Comment by muammar** [comment]
> I have fixed this and this is now merged into master.

Thanks for the fix. If the problem gets solved, feel free to close this issue.
