### ISSUE TITLE
"No devices found" for a miracast device

### ISSUE THREAD

**Issue by terdon** [muammar/mkchromecast#26]
First of all, thank you for this! 

I am trying to connect to my miracast device (see below for hardware details) but get the following:

```
$ mkchromecast 
mkchromecast v0.3.6
Creating pulseaudio sink...
Open pavucontrol and select the mkchromecast sink.
Starting local streaming server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz
PID of main process: 8629
PID of streaming process: 8832
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
No devices found!
/sbin/mkchromecast: line 9:  8629 Killed                  python /usr/share/mkchromecast/mkchromecast.py
```

I am testing this on Arch Linux, the sink does briefly appear in pavucontrol so the only issue seems to be that it doesn't detect the device. The device is seen by Android ([BubbleUPnP](http://www.bubblesoftapps.com/bubbleupnpserver/)) and iOS devices (AirPlay) so I assume it should also be seen by mkchromecast. 

I looked at your code and as far as I can tell, the device list is being returned  by the `get_chromecasts_as_dict` function which is provided by `pychromecast`. Is there any way to get this to find my device or does `pychromecast` support chromecast devices exclusively and no miracast?

In case it matters, the hardware specs of my device are shown below. The device itself is from a local (Greek) manufacturer and its manual gives the following specs (translated to the best of my ability):

```
Miracast TV dongle
CPU                              AM8251
RAM                             DDR3 128M
ROM                             Flash 128M
Power Supply               ≤ 400mA@5V
OS                                Linux
Supports                       EZCast, Airplay, Miracast, DLNA
Wi-Fi                             IEEE 802.11 b/g/n
Audio                            WMA/WAV/OGG/AAC/FLAC/3GP...
Video                            MP4/MKV/AVI/RM/RMVB/MOV/TS...
Images                         JPEG/JPG/BMP/PNG/GIF/TIFF...
Βίντεο 
Supported OSs            Android  : Android4.0 or later
                                    IOS         : IOS6 or later
                                    Mac         : Mac10.7
                                    Windows : WinXP/7/8
Make                           TURBO-X
```

**Comment by muammar** [comment]
> I looked at your code and as far as I can tell, the device list is being returned by the get_chromecasts_as_dict function which is provided by pychromecast. Is there any way to get this to find my device or does pychromecast support chromecast devices exclusively and no miracast?

Thanks for your interest in **mkchromecast**. I am afraid that pychromecast only works with google cast devices. Miracast is not supported. There is not too much I could do...

**Comment by muammar** [comment]
I am proceeding to close this report. Please, reopen it if you consider it necessary. Thanks.

**Comment by terdon** [comment]
Argh, sorry, just realized I never replied to you. Yes, of course, this should be closed. Thanks for you reply and the work you've put in, even if it doesn't work for my device :).

**Comment by muammar** [comment]
Thank you!. Maybe you should try https://github.com/masmu/pulseaudio-dlna that is a wider solution. :) Happy holidays.
