### ISSUE TITLE
Dalay over 1 minute

### ISSUE THREAD

**Issue by IWantOriginalName** [muammar/mkchromecast#260]
Hi! I Install your mkcromecast on Manjaro (Arch Linux). All working, but I have delay over 1 minute... How can I fix it?
I use pulseaudio and Spotify.

**Comment by muammar** [comment]
> Hi! I Install your mkcromecast on Manjaro (Arch Linux). All working, but I have delay over 1 minute... How can I fix it?
> I use pulseaudio and Spotify.

Have you tried different encoders?

**Comment by viktorsmari** [comment]
@muammar The readme says:
> When using parec and lame encoder, the delay between audio played and listened can be up to 8 seconds. I suggest you to use something different than mp3.

Is the `ffmpg` better?

Could we add a **suggested way** for the lowest delay in the Readme?
In the issues it looks some brilliant people have been testing these out, and it would be nice to have their suggestions on which backend / coding format / bitrate / etc is optimal for a low delay.

**Comment by TheRoarkster** [comment]
@muammar Is there an "optimal settings" suggestion for lowest delay?

**Comment by smalchow** [comment]
Hi,

i am experimenting with the delays ass well, one thing i could not test, because it is not supported by mkchromecast as long as i can see, is to use other ffmpeg preset, the default preset is medium, how about trying "ultrafast" in a LAN environment i do not really care about the amount of data.

Cheers
Soeren

**Comment by muammar** [comment]
> ultrafast

Where should this go?

**Comment by muammar** [comment]
I am trying to unify this: See https://github.com/muammar/mkchromecast/issues/292.
