### ISSUE TITLE
Ubuntu 16.10 not working

### ISSUE THREAD

**Issue by cdekok** [muammar/mkchromecast#28]
I installed it through apt-get only when i search for the app and launch it nothing happens?
I should get an icon in the toolbar on top right ?

**Comment by muammar** [comment]
Yes. That's correct. Could you open the terminal and launch it as follows:

```
mkchromecast -t
```

And paste the output here. Thanks for reporting.

**Comment by cdekok** [comment]
It seems to be failing on a ssl python module.

```
➜  cms-ts git:(master) ✗ mkchromecast -t
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 8, in <module>
    from mkchromecast.cast import *
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 13, in <module>
    import pychromecast
  File "/usr/lib/python2.7/dist-packages/pychromecast/__init__.py", line 12, in <module>
    from .config import *  # noqa
  File "/usr/lib/python2.7/dist-packages/pychromecast/config.py", line 6, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

**Comment by muammar** [comment]
Can you verify if you have the `python-requests` debian package?. If yes, then uninstall requests using pip:

```
pip uninstall requests
```

Does it work?.

Source: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781781

**Comment by cdekok** [comment]
I could not uninstall it but it works after

```
 pip install --user requests
```

When trying to uninstall it I get a warning about permissions on:
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/requests'

When try to remove it as sudo I get a warning that the files under user where owned by a different user.

Anyway was it seems a debian bug I will close it ;)

**Comment by muammar** [comment]
Thanks for reporting back. Yes, you are right. It is a debian packaging issue instead. I will add your report to the FAQ so that others can benefit from it.
