### ISSUE TITLE
BlackHole instead of Soundflower possible?

### ISSUE THREAD

**Issue by HobbinHood** [muammar/mkchromecast#289]
System: macOS 10.14
Would it be possible to use https://github.com/ExistentialAudio/BlackHole instead of Soundflower?

**Comment by muammar** [comment]
Interesting. I will take a look at that. Probably, yes?

**Comment by HobbinHood** [comment]
Cool. Hope(d) so. Wasn't really sure how intertwined mkchromecast is with controlling Soundflower on the technical level.
When confirmed, I can/will update the homebrew files to either have blackhole or soundflower as dependency.
Thank you.

**Comment by muammar** [comment]
audio devices are changed with these functions: 

https://github.com/muammar/mkchromecast/blob/master/mkchromecast/audio_devices.py

I think the `audiodevice` binary would need some changes. That is the only limitation I see right now.

**Comment by HobbinHood** [comment]
Maybe I'm misunderstanding this: Isn't the `audiodevice` binary from Soundflower? Why would it need changes if we try to replace Soundflower with BlackHole?

**Comment by muammar** [comment]
It's done now. See https://github.com/muammar/mkchromecast/commit/0fbfcc77b706d2077fc0e737f681b056f3e14b06. Let me know if this worked for you, too.

**Comment by HobbinHood** [comment]
Thank you kindly o/
