### ISSUE TITLE
No command line binary with macOS package

### ISSUE THREAD

**Issue by norey** [muammar/mkchromecast#303]
I installed mkchromecast from homebrew and only the system tray version got installed. I'm looking for the CLI version so I tried cloning the repo and running it:

```
$ bin/mkchromecast
Mkchromecast v0.3.9
Selected backend: node
Default bitrate used: 192k.
Default sample rate used: 44100Hz.
PID of main process: 11862
PID of streaming process: 11865
internal/modules/cjs/loader.js:955
  throw err;
  ^

Error: Cannot find module '/Users/user/Downloads/mkchromecast/nodejs/node_modules/webcast-osx-audio/bin/webcast.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Reconnecting node streaming...
```
I tried `pip3 install -r requirements.txt` thinking that some dependency was missing, it started spitting a lot of errors on the `PyGObject-3.36.0.tar.gz` package so I stopped.

Why doesn't the CLI binary come with the macOS package?

**Comment by PhilipGarnero** [comment]
Use this as the path when installing with cask `/Applications/mkchromecast.app/Contents/MacOS/Mkchromecast`
