### ISSUE TITLE
very long lag in Solus

### ISSUE THREAD

**Issue by vyzle** [muammar/mkchromecast#306]
Hi,
Mkchromecast is available through Solus package manager so I thought it would run ok.
However, I can start it fine from the terminal. The option to switch over to mk output is in sound control settings. When I start mk I get the audio BLOOP confirmation. But playing any audio has a very long lag. 20 plus seconds.
There is a warning on app startup about using a production server but I don't see a setting to change server.
Should I change the back end?
Any ideas?
Many thanks

**Comment by PhilipGarnero** [comment]
There is currently a lag issue opened in pychromecast : https://github.com/home-assistant-libs/pychromecast/issues/356

**Comment by muammar** [comment]
Unifying here: https://github.com/muammar/mkchromecast/issues/292

**Comment by muammar** [comment]
Note that I pushed a commit that decreased the lag considerably for me. @vyzle you might try it.

**Comment by vyzle** [comment]
Thank you!
