### ISSUE TITLE
cannot import name 'DependencyWarning

### ISSUE THREAD

**Issue by rikmendes** [muammar/mkchromecast#31]
I'm getting this when I launch mkchromecast : 

```
Traceback (most recent call last):
  File "/usr/share/mkchromecast/mkchromecast.py", line 8, in <module>
    from mkchromecast.cast import *
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 13, in <module>
    import pychromecast
  File "/usr/lib/python3.5/site-packages/pychromecast/__init__.py", line 12, in <module>
    from .config import *  # noqa
  File "/usr/lib/python3.5/site-packages/pychromecast/config.py", line 6, in <module>
    import requests
  File "/usr/lib/python3.5/site-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
```

My system is Arch Linux I have followed the this instruction to get it installed : https://github.com/muammar/mkchromecast#arch-linux

the compile seemed to be going fine, no errors, nothing interrupted the compilation but
when I execute mkchromecast I still have missing dependencies. 

Using Python 3.5.2

**Comment by muammar** [comment]
Hi Rick. Thanks for the report. Have you seen this? https://github.com/nickoala/telepot/issues/80 it seems to be a problem with `requests` in Arch.  Can you confirm if reinstalling requests does something in your case?

I will contact the responsible of the Arch package so that he updates it.

**Comment by rikmendes** [comment]
Hi @muammar I have followed the instruction from your link and it helped I think to solve the issue. 
now I can python mkchromecast.py -t and have the systray & cast running fine !

Thanks for this little gem of code, I was looking for this for a while !

**Comment by muammar** [comment]
>Hi @muammar I have followed the instruction from your link and it helped I think to solve the issue.
now I can python mkchromecast.py -t and have the systray & cast running fine !

Glad it worked :) I think I will add your report to the FAQ so that others can benefit from it. 

>Thanks for this little gem of code, I was looking for this for a while !

Thanks for your compliment!. I will update it soon, and add more options without losing the main idea of the app: the simpler the better. Nice to know this thing is useful for others. Enjoy!.

**Comment by terencode** [comment]
Hey I'm the maintainer of the Arch package.
Glad to know it's working now and you can also call the application from anywhere directly with `$ mkchromecast -t` to start the tray for instance ;)

**Comment by terencode** [comment]
Even easier, if you are using a distribution using .desktop files like GNOME and KDE, the package actually creates one to be able to start mkchromecast in tray mode quickly.
