### ISSUE TITLE
Minor bug in [dfeaf2e] if not using sonos

### ISSUE THREAD

**Issue by iliasptr** [muammar/mkchromecast#310]
Hi,
I would like to let you know about a minor issue with [dfeaf2e](https://github.com/muammar/mkchromecast/commit/dfeaf2e9c8d073f72aea058b5306482d574b0718).
On `mkchromecast/cast.py` line 111, `zone` is `None` and this leads to an `AttributeError` in line 113:
```
    self.sonos_list = zone.all_groups
AttributeError: 'NoneType' object has no attribute 'all_groups'
```
I imagine that this is because I am using a Chromecast Audio and not Sonos. Nevertheless, The `soco` package is installed as part of the requirements, so we still pass by the Sonos `try` block.

Either putting lines 113-117 under an `if zone is not None:` statement or adding an `AttributeError` in the exception below can easily fix this problem.

Thanks for the great package btw. I am looking forward to any further delay reduction after your discussion in #292. With the `wav` codec, I currently have 3-4seconds delay on fedora 32 but any further delay reduction would be cool, as this is still too much for movies etc.

**Comment by muammar** [comment]
Thanks, I fixed that. However, the systray is broken when you want to use Sonos. One step at a time.

**Comment by sah-anshu** [comment]
Hi, Systray is still broken Can't stream to SONOS.

```
Casting to: Sonos Roam
 
pcastready ? _play_cast_ failed
Traceback (most recent call last):
  File "/home/anshu/Projects/mkchromecast/bin/../mkchromecast/systray.py", line 508, in stop_cast
    self.cast.quit_app()
AttributeError: 'NoneType' object has no attribute 'quit_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anshu/Projects/mkchromecast/bin/../mkchromecast/systray.py", line 479, in pcastready
    self.stop_cast()
  File "/home/anshu/Projects/mkchromecast/bin/../mkchromecast/systray.py", line 512, in stop_cast
    self.cast.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
Aborted (core dumped)
```
