### ISSUE TITLE
Play a movie from a given time

### ISSUE THREAD

**Issue by szilagyi314** [muammar/mkchromecast#317]
Dear Muammar,
I am in Ubuntu and I can play any local film or youtube from command prompt.
e.g.: mkchromecast --video -i "movie.mp4"
I would like to know if there is a way
to play a movie from a given time or
interval instead of always from beginning to end?
Brgds/Laci

**Comment by muammar** [comment]
That can be done this way: 

```
  --seek SEEK
                            Option to seeking when casting video. The format to set the time is
                            HH:MM:SS.

                            Example:
                                python mkchromecast.py --video -i "/path/to/file.mp4" --seek 00:23:00
```

**Comment by szilagyi314** [comment]
Dear Muammar,

Thank you for your quick reply on my previous question.
(Now I see I could find it under --help option also.)

Now I would like to know if there is an application to control the
chromcast hw. (next to the TV) by an Android smart phone.
Now I tried with GoogleHome but it can control only the volume of hw.
So I think for an Android app. that tells to hw. to stop or seek back 10sec,
and the google chrom hw. communicates with your mkchromcast as it happens at native youtube playing or using the BubbleUPnP for DLNA/Chromecast/Smart TV.

Brgds/Laci
