### ISSUE TITLE
Can I use mkchromecast to set up a wireless display?

### ISSUE THREAD

**Issue by pavlovdog** [muammar/mkchromecast#318]
I have a laptop and a second display, which is connected through the HDMI. It would be great if I could use the second display wirelessly - with Chromecast. Can mkchromecast do this? I know that I can cast a specific window with a Chrome extension, but I want to share the whole workspace without running a browser.

![image](https://user-images.githubusercontent.com/5871170/84924455-3611a180-b0d1-11ea-9ccb-14dd3124eba0.png)

Thanks in advance!

**Comment by muammar** [comment]
This is not possible with Mkchromecast. Even if it was possible, I guess the delay between taking action and seeing the response would be substantial.
