### ISSUE TITLE
can't cast to my google audio chromecast

### ISSUE THREAD

**Issue by miloit** [muammar/mkchromecast#34]
Hello my ~/.asoundrc needs to look like

 

    pcm.snd_card {

        type hw

        card 0

        device 3

    }

    ctl.snd_card {

        type hw

        card 0

        device 3

    }

 

So that I can hear some sound through my HDMI.

 

Aplay –l looks like

 

    % cat /proc/asound/cards                                                                                                                             
     0 [HDMI            ]: HDA-Intel - HDA Intel HDMI
                      HDA Intel HDMI at 0xc1814000 irq 57
     1 [PCH             ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xc1810000 irq 61

 My /etc/pulse/client.conf

    autospawn=no

How do I need to configure the .asoundrc file that I can cast my audio through my chromecast?

**Comment by muammar** [comment]
> Aplay –l looks like

Can you post the output of this command?. For me it looks like:

```
muammar@zarathustra ~   % aplay -l                                                                                                                                           
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 0: CS4208 Analog [CS4208 Analog]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 1: CS4208 Digital [CS4208 Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

We need to know the `card` and `Subdevice` to do the `Loopback`.

**Comment by miloit** [comment]
**** Liste der Hardware-Geräte (PLAYBACK) ****
Karte 0: HDMI [HDA Intel HDMI], Gerät 3: HDMI 0 [HDMI 0]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 0: HDMI [HDA Intel HDMI], Gerät 7: HDMI 1 [HDMI 1]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 1: PCH [HDA Intel PCH], Gerät 0: ALC283 Analog [ALC283 Analog]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0

**Comment by muammar** [comment]
Try the adding this to your `~/.asoundrc`  file:

```
pcm.!default {
  type asym
  playback.pcm "LoopAndReal"
  #capture.pcm "looprec"
  capture.pcm "hw:1,0"
}

pcm.looprec {
    type hw
    card "Loopback"
    device 1
    subdevice 0
}


pcm.LoopAndReal {
  type plug
  slave.pcm mdev
  route_policy "duplicate"
}


pcm.mdev {
  type multi
  slaves.a.pcm pcm.MixReale
  slaves.a.channels 2
  slaves.b.pcm pcm.MixLoopback
  slaves.b.channels 2
  bindings.0.slave a
  bindings.0.channel 0
  bindings.1.slave a
  bindings.1.channel 1
  bindings.2.slave b
  bindings.2.channel 0
  bindings.3.slave b
  bindings.3.channel 1
}


pcm.MixReale {
  type dmix
  ipc_key 1024
  slave {
    pcm "hw:1,0"
    rate 48000
    #rate 44100
    periods 128
    period_time 0
    period_size 1024 # must be power of 2
    buffer_size 8192
  }
}

pcm.MixLoopback {
  type dmix
  ipc_key 1025
  slave {
    pcm "hw:Loopback,0,0"
    rate 48000
    #rate 44100
    periods 128
    period_time 0
    period_size 1024 # must be power of 2
    buffer_size 8192
  }
}
```

Then, load this module:

```
sudo modprobe snd-aloop
```

You should see something similar to what is described here: https://github.com/muammar/mkchromecast/wiki/ALSA#how-to-determine-hwx2y2-and-the-loopback-device. **Verify the index of your `Loopback`**.

Then, try:

```
python mkchromecast.py --encoder-backend ffmpeg --alsa-device hw:2,1 -c aac --volume
```

If the configuration does not work, try changing from `hw:1,0` to `hw:0,0`.

**Comment by miloit** [comment]
`pcm.!default {
        type hw
        card 0
        device 3
}

ctl.snd_card {
        type hw
        card 0
        device 3
}
pcm.!default {
  type asym
  playback.pcm "LoopAndReal"
  #capture.pcm "looprec"
  capture.pcm "hw:1,0"
}

pcm.looprec {
    type hw
    card "Loopback"
    device 1
    subdevice 0
}


pcm.LoopAndReal {
  type plug
  slave.pcm mdev
  route_policy "duplicate"
}


pcm.mdev {
  type multi
  slaves.a.pcm pcm.MixReale
  slaves.a.channels 2
  slaves.b.pcm pcm.MixLoopback
  slaves.b.channels 2
  bindings.0.slave a
  bindings.0.channel 0
  bindings.1.slave a
  bindings.1.channel 1
  bindings.2.slave b
  bindings.2.channel 0
  bindings.3.slave b
  bindings.3.channel 1
}


pcm.MixReale {
  type dmix
  ipc_key 1024
  slave {
    pcm "hw:1,0"
    rate 48000
    #rate 44100
    periods 128
    period_time 0
    period_size 1024 # must be power of 2
    buffer_size 8192
  }
}

pcm.MixLoopback {
  type dmix
  ipc_key 1025
  slave {
    pcm "hw:Loopback,0,0"
    rate 48000
    #rate 44100
    periods 128
    period_time 0
    period_size 1024 # must be power of 2
    buffer_size 8192
  }
}
`



doesn`t work

**Comment by muammar** [comment]
> I use

> `sudo  mkchromecast --encoder-backend ffmpeg --alsa-device hw:2,1 -c aac --volume`

`sudo` is not needed to launch the application. Can you retry without sudo?. If it does not work, can you change from `hw,0,0` to `hw,1,0` and let me know if it works for you?.

**Comment by miloit** [comment]
No i don't hear anything

**Comment by ao-il** [comment]
Music player like audacious or clementine can allow you to choose which card to use for playback. In my case, I use audacious since it's lighter. I don't need .asoundrc but only load snd-aloop module and then select Loopback 1,0 as playback device in audacious and hw:1,1 as ffmpeg input.

**Comment by muammar** [comment]
Closing this report due to inactivity.

**Comment by johanmil** [comment]
Hi! I'm having trouble configuring my .asoundrc file according to my specs. I want to route my line-in audio, from an USB sound card, to my chromecasts. My wish is to do this with ALSA, so that i can avoid having to use Pulseaudio to select the correct sink. I've tested Pulseaudio which worked perfectly.

This is my /proc/asound/cards : 

>  0 [Loopback       ]: Loopback - Loopback
                      Loopback 1
 1 [ALSA           ]: bcm2835_alsa - bcm2835 ALSA
                      bcm2835 ALSA
 2 [Device         ]: USB-Audio - USB Audio Device
                      GeneralPlus USB Audio Device at usb-3f980000.usb-1.1.3, full speed

I am aware of issue #203, however when I chage the alsa-base.conf file the following happens:

>   0 [ALSA           ]: bcm2835_alsa - bcm2835 ALSA
                      bcm2835 ALSA
1 [Loopback       ]: Loopback - Loopback
                      Loopback 1
 2 [Device         ]: USB-Audio - USB Audio Device
                      GeneralPlus USB Audio Device at usb-3f980000.usb-1.1.3, full speed

Are you or someone else willing to provide me with the correct hw:X1,Y1 and hw:X2, Y2 values? 

Many thanks!
