### ISSUE TITLE
py2app giving abort trap 6

### ISSUE THREAD

**Issue by muammar** [muammar/mkchromecast#36]
It is not being possible to create a macOS app this time. Maybe it is a good time to switch from `py2app` to `pyinstaller`?.  This bug is holding back the release.

**Comment by PePeHa** [comment]
i am not a developer, so cant help you on this, Muammar. but could it be that my ffmpeg issue is related to MacOS changes too ? similar to your problem ?

**Comment by muammar** [comment]
> i am not a developer, so cant help you on this, Muammar. but could it be that my ffmpeg issue is related to MacOS changes too ? similar to your problem ?

No. This problem is related to `py2app` not being capable of freezing correctly a macOS app. I have tried with another tool called `pyinstaller` but then it seems that now all applications to run on macOS need to be signed... If this is the case, I will drop support creating a macOS app.

**Comment by PePeHa** [comment]
thanks Muammar. Apple seems to make things more and more difficult on MacOS. i hope this can be  resolved.

**Comment by muammar** [comment]
With `qt 5.8`, the app is created but it is failing with the following error:

```
MFI: allowing exception handler for 'mkchromecast' (18786) because the process is unsigned.
```

**Comment by muammar** [comment]
Now the application is compiled. But there is a problem with Qt.

**Comment by muammar** [comment]
Finally, there is a tool here https://github.com/iltommi/macdeployqtfix that fixes the problem. I am closing this report and will prepare `0.3.7`.˜
