### ISSUE TITLE
one step towards Pipewire

### ISSUE THREAD

**Issue by frankenstein91** [muammar/mkchromecast#362]
Currently I have found a dependency on pacmd. I use pipewire on my system and it only supports pactl. Would it be possible to change the affected commands?

A translation table is available: https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Migrate-PulseAudio#pacmd

Thank you

**Comment by itaranto** [comment]
I replaced the `pacmd` calls with `pactl` and it seems to work fine.   
I created this merge [request](https://github.com/muammar/mkchromecast/pull/368).

**Comment by muammar** [comment]
I merged your pull request, @itaranto . Thanks.
