### ISSUE TITLE
Chromecast Audio support up to 24-bit / 192kHz

### ISSUE THREAD

**Issue by PePeHa** [muammar/mkchromecast#39]
Chromecast Audio accepts up to 24-bit / 192kHz PCM .wav and .flac files via (amongst others UPnP Server) and plays them in full resolution. Could we add 24-bit support at different sample rates, including 88.2kHz, 96kHz, 176.4kHz and 192kHz into this mkchromecast project ? And if possible, could we also add the preferred bit-depth and sample rate to the dropdown menu ?

**Comment by muammar** [comment]
Thanks for your report. 192khz in mkchromecast it is not a problem to be implemented ([see here](https://github.com/muammar/mkchromecast/issues/11)). 

Regarding bit-depth, I think that that has to be set explicitly by users. For instance, if using pulseaudio, one has to change some configuration files to modify it to the desired bit-depth. If I am not wrong, the same would be in macOS.

**Comment by PePeHa** [comment]
thnx muammar. great project. for your information, on MacOS, sending 24-bit / 192kHz over DLNA / UPnP to Chromecast Audio did not require any additional settings. the only thing to set is the sample rate in Soundflower, and Soundflower uses the internal 32-bit regardless of chosen samplerate (it just fills unused bits with zero's, so the effective bit-depth depends on the bit-depth of the source file or stream you are sending out, using Soundflower as your audio device).

PS - also read my other comment. at the moment i can not get anything working in ffmpeg on mkchromecast; only node.js works up to 320kbps (500kbps not working in node.js either). i really would like to use flac 44.1kHz and higher via ffmpeg. what am i doing wrong ? see my other question

**Comment by muammar** [comment]
>thnx muammar. great project. for your information, on MacOS, sending 24-bit / 192kHz over DLNA / UPnP to Chromecast Audio did not require any additional settings. the only thing to set is the sample rate in Soundflower, and Soundflower uses the internal 32-bit regardless of chosen samplerate (it just fills unused bits with zero's, so the effective bit-depth depends on the bit-depth of the source file or stream you are sending out, using Soundflower as your audio device).

As far as I understand it, you are correct. 

>PS - also read my other comment. at the moment i can not get anything working in ffmpeg on mkchromecast; only node.js works up to 320kbps (500kbps not working in node.js either). i really would like to use flac 44.1kHz and higher via ffmpeg. what am i doing wrong ? see my other question

With `node`, the library used does not allow to set something higher than 320kpbs for mp3. However when I was researching about it, mp3 with such high bitrate is not very nice to use. For those cases it is better going to lossless formats. Getting back to your ffmpeg problem, can you open a terminal and execute the following:

```
which ffmpeg
``` 

Can you post what that command prints, please?.

**Comment by muammar** [comment]
**mkchromecast** looks for `ffmpeg` in the [PATH shown here](https://github.com/muammar/mkchromecast/blob/c9af7bf0a6e2e6a87cd2defaa353a45044821816/mkchromecast/preferences.py#L22).

**Comment by PePeHa** [comment]
Muammar, you are great ! thanks for helping me. i ran "which ffmpeg" in terminal, and got this as response: "/usr/local/bin/ffmpeg". 

In addition, i also ran "ffmpeg" in terminal,  and got this as response:
"ffmpeg version 3.2.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.2.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-opencl --disable-lzma --enable-nonfree --enable-vda
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100"

Muammar, i'm looking forward to your solution ! you are great ! thanks

**Comment by PePeHa** [comment]
by the way: /usr/local/bin has a symlink to the installation of ffmpeg, which resides in /usr/local/cellar, as shown above.

**Comment by PePeHa** [comment]
Muammar, any idea ?

**Comment by muammar** [comment]
@PePeHa  I have implemented support for 192kHz. See https://github.com/muammar/mkchromecast/commit/1aad081c7bfe62446138abf5cfe78a1e03e38d16. Let's discuss the problem related to ffmpeg in your other report.
