### ISSUE TITLE
"Illegal instruction: 4" when launching on OS X

### ISSUE THREAD

**Issue by glimpsed** [muammar/mkchromecast#4]
When I tried running mkchromecast on OS X 10.11 or 10.6, the app crashes with an "Illegal instruction: 4" error.

It also generates this message in the Console:
5/27/16 5:38:39.333 PM com.apple.xpc.launchd[1]: (com.mkchromecast.osx.1974432[2842]) Service exited due to signal: Illegal instruction: 4

I've also attached the crash report below:
[mkchromecast_2016-05-27-173851_Sergius-Mac-Pro.txt](https://github.com/muammar/mkchromecast/files/286652/mkchromecast_2016-05-27-173851_Sergius-Mac-Pro.txt)

**Comment by muammar** [comment]
"The "illegal instruction" message is simply telling you that your binaries contain instructions the version of the OS that you are attempting to run them under does not understand.".[1]

I am aware of this problem. I saw it when creating the app in my macbook pro 2015, and launching it in older models. To tackle it, I used another Macbook pro from 2011 (model 8,2) to build the binary that is being currently shipped. 

@glimpsed could you tell the model of your mac to discard this as the cause of the problem?. I have to accept that I am trying to build a universal application with `py2app` but your report is a prove that it is not working. I will investigate it in more details. 

A way to solve this locally, would be to use the `Makefile` shipped in the git repo, and do a `make deploy` to build the binary. It will require you to install  `pyqt5` using  `brew` as described in the README, and the packages inside `requirements.txt` (except of course pyqt5). Additionally, you would need to install using `pip` these packages: 

```
pip install bs4 google py2app
```

After that, the `make deploy` would create a standalone app that should work in your machine. I will write something in the wiki regarding this. 

Thanks for your report.

[1] http://stackoverflow.com/a/14269066/1995261

**Comment by glimpsed** [comment]
I have a Mac Pro (Early 2009), model identifier MacPro4,1, running OS X 10.11. 

I've also tested the app on an older test machine, an iMac (20-inch, Late 2006) running OS X 10.6.8 to see if the problem is the OS X version.

**Comment by glimpsed** [comment]
@muammar I will also try building a mkchromecast binary on my machine to see if the problem persists.

**Comment by muammar** [comment]
@glimpsed thank you for this valuable information. So this confirms that the app I created is like "semi standalone". It won't work for models below 2011. I have prepared the [instructions to build the app](https://github.com/muammar/mkchromecast/wiki/Mac-standalone-app). In the meanwhile, I will keep investigating how to fix this in the `setup.py` file for `py2app`. 

Thanks for building the binary on your machine. If it works, you could pass it to me to publish it, so that people with your model can use it. 

Cheers.

**Comment by muammar** [comment]
@glimpsed I forgot to mention that the app is built using `python3`. I have updated that in the instructions. AFAIK, pyqt5 + python2 using `py2app` does not play very well.

**Comment by glimpsed** [comment]
@muammar Thanks. Unfortunately though, even with python3 installed i couldn't build the binary for mkchromecast on my machine.

First of all pip didn't install all the dependencies, therefore I had to use easy_install to do it. However, `make deploy` failed to build the binary saying that there is no python3 installation in `/usr/local/opt`.

I don't really know what the problem is, therefore, at this moment, I hope you can build a truly standalone version of the mkchromecast app.

**Comment by muammar** [comment]
Hi @glimpsed I think I have found a solution to the problem. Could you please try using this binary, please? https://drive.google.com/file/d/0BxT_3XOg2MENR05BcjNvQmRZb28/view?usp=sharing

Tell me if it works for you. I had to create a virtualbox  machine emulating an old processor. It works fine in my laptop, it should work in yours as well. 

Cheers,

**Comment by glimpsed** [comment]
@muammar Yes, this version works. Thank you :+1:

**Comment by muammar** [comment]
Thanks for testing :). Glad it worked. Cheers.

**Comment by sandvige** [comment]
@muammar Could you elaborate your solution? Isn't it possible to compile things with the correct options on recent machines?

**Comment by muammar** [comment]
@sandvige I tried changing some of the options [here](https://github.com/muammar/mkchromecast/blob/master/setup.py#L66), and nothing worked. I ended up installing macOS on a VirtualBox machine, and creating the app there. As VirtualBox will emulate an old processor, then your bundle will work in the vast majority of Apple hardware as far as I can tell. I hope this helps you.

**Comment by sandvige** [comment]
Ok thanks! I will try to boot a Mac OS X VM in VirtualBox... it looks like it's not that easy to do... Should I use that kind of things: https://techsviewer.com/install-macos-sierra-virtualbox-windows/ ? This looks a bit hacky :(

**Comment by muammar** [comment]
@sandvige yes, that's what I used. But you know, I suggest you use Yosemite instead of Sierra. Because then it creates problems if you do it in Sierra. For some reason, if you use Sierra, then the bundle won't run in macOS < Sierra **sigh**. 

https://techsviewer.com/install-mac-os-x-10-10-yosemite-retail-on-vmware-on-pc/

**Comment by sandvige** [comment]
Awesome, thanks!

**Comment by sam1penny** [comment]
I also have this problem and i was wondering if you deleted this file or if the link is wrong?
(you attached this file a few comments up)
https://drive.google.com/file/d/0BxT_3XOg2MENR05BcjNvQmRZb28/view?usp=sharing
