### ISSUE TITLE
mkchromecast stop working when ubuntu firewall was activated

### ISSUE THREAD

**Issue by pedroalvess** [muammar/mkchromecast#42]
First. Thanks for the software. Very good.
I need to program the firewall for an exception. What I must do?
Thanks.

Pedro

**Comment by muammar** [comment]
You will need port `5000` to accept connections. Check out this [Allow or block specific network activity](https://help.ubuntu.com/stable/ubuntu-help/net-firewall-on-off.html). The command may be something like:

```
sudo ufw allow 5000
```

Tell me if it works to update the documentation.

**Comment by pedroalvess** [comment]
Thanks.
It is port 5000 TCP.
It is working!

Obter o Outlook para Android<https://aka.ms/ghei36>


________________________________

**Comment by muammar** [comment]
You are welcome! I will update the FAQ and then I will close this. :). HAppy casting.
