### ISSUE TITLE
mkchromecast starts, but doesn't show the tray menu or any stdout

### ISSUE THREAD

**Issue by gradecke** [muammar/mkchromecast#45]
Hi,

maybe I'm overlooking something really obvious, but on my pretty fresh mac os sierra install, the current mkchromecast 0.3.6 installed from dmg opens without any error, however I don't get to see a tray menu or find any other way to interact with it. (Soundflower 2.02b is installed via homebrew)

I tried a few cli parameters but nothing except "-r" makes any difference. And -r just kills the process immediately.

Console doesn't show anything that is looks particularly special to me

![bildschirmfoto 2017-02-02 um 21 21 16](https://cloud.githubusercontent.com/assets/3447561/22566811/bdc9d278-e98d-11e6-8a9d-ccb720c20e6d.png)

Not sure what other information I can provide to help troubleshoot this.

Can you help?

Regards, Gerd

**Comment by muammar** [comment]
> Hi,
>
> maybe I'm overlooking something really obvious, but on my pretty fresh mac os
> sierra install, the current mkchromecast 0.3.6 installed from dmg opens without
> any error, however I don't get to see a tray menu or find any other way to
> interact with it. (Soundflower 2.02b is installed via homebrew)
>
> I tried a few cli parameters but nothing except "-r" makes any difference. And
> -r just kills the process immediately.
>
> Console doesn't show anything that is looks particularly special to me
>
> bildschirmfoto 2017-02-02 um 21 21 16
>
> Not sure what other information I can provide to help troubleshoot this.
>
> Can you help?

I think this is related to issue #36. To be honest, apple is making it difficult
to share applications that are not signed.

Your problem is similar with what I reported in #36 because the application
fails because it is not signed. In order to sign the application, I think
I would need to enroll in apple developer's program that has certain fee that
I won't pay and the only donations I have received are not enough to buy it:).
That being said, I will  need to research more about that.

For the moments, you may try to use the application from sources as it is
described on the README.md file.

**Comment by gradecke** [comment]
Thanks for your quick reply!

pyqt5 with qt 5.7 currently doesn't brew on Sierra, but it looks like this issue is very new and being worked on (http://apple.stackexchange.com/questions/270302/in-sierra-how-to-get-qt-5-8-0-pyqt-5-7-1-sip-4-19-python3-5-to-install) , so I'll try again in a few days and update this issue accordingly

**Comment by muammar** [comment]
>Thanks for your quick reply!

You are welcome!.

>pyqt5 with qt 5.7 currently doesn't brew on Sierra, but it looks like this issue is very new and being worked on (http://apple.stackexchange.com/questions/270302/in-sierra-how-to-get-qt-5-8-0-pyqt-5-7-1-sip-4-19-python3-5-to-install) , so I'll try again in a few days and update this issue accordingly

You can use `5.8`. I will update the readme. Sorry about that!.

**Comment by muammar** [comment]
Maybe this could help to allow the application to run? 

http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/

**Comment by gradecke** [comment]
Unfortunately, that makes no difference. I don't think Gatekeeper is the problem, as that would prevent mkchromecast from starting at all, right? However, in my case I can see a process in the dock and the two entries in the console log, just nothing afterwards. Will try recompiling with a hopefully working QT on the weekend :) 

Thanks for you help!

**Comment by gradecke** [comment]
Hi, not sure what changed but I downloaded the dmg again today and installed it and now everything works perfectly. But as far as I can see, it's still 0.3.6. I did a "brew upgrade" before but not sure if that is related. If I can provide any helpful information, please let me know.

Cheers, 
 Gerd

**Comment by muammar** [comment]
That is weird :). But glad it worked. I haven't been able to build a new dmg using py2app. :( If you would like to use newer versions, you may use the application from source. There is another way https://github.com/muammar/mkchromecast/wiki/macOS-standalone-app
