### ISSUE TITLE
parec backend problem Ubuntu 16.04

### ISSUE THREAD

**Issue by PeterDyce** [muammar/mkchromecast#46]
Hi, thanks for mkchromecast. Its  a great little application.
I followed your instructions for my linux os and everything installed fine

Everything seems to run ok too however I  found I had a problem  using the default 'parec'
back end. everything works like a charm if I use "ffmpeg".
 I'm still trying to work why. Can you offer any suggestions on debugging  mkchromecast while using the parec backend.

Peter

**Comment by muammar** [comment]
>Everything seems to run ok too however I found I had a problem using the default 'parec'
back end. everything works like a charm if I use "ffmpeg".
I'm still trying to work why. Can you offer any suggestions on debugging mkchromecast while using the parec backend.

What is the issue you are getting with `parec`?. No sound casted?. Are you using the github version or the package?.

**Comment by muammar** [comment]
Do you still have the problem with parec?

**Comment by PeterDyce** [comment]
Hi yes I'm afraid I haven't bothered to follow this up.
I found the ffmpeg option  worked fine. so being a lazy I took the path of least resistance
Sorry should have replied earlier.

**Comment by muammar** [comment]
>Hi yes I'm afraid I haven't bothered to follow this up.
I found the ffmpeg option worked fine. so being a lazy I took the path of least resistance
Sorry should have replied earlier.

LOL. Don't worry. :) I will proceed to close this report. Feel free to re-open it if you think it is necessary.
