### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by chasgithub** [muammar/mkchromecast#48]
Fresh install of lubuntu (16.10 Yakkety).  I install mkchromecast 3.6-3.  Installed dependencies just to be sure. Runs fine, but always says "No Cast Devices Found" in tray control. 

Chrome browser on same machine can find all cast devices, no problem.

Any tips to clear up this problem?   (I had this working a while ago on 16.04)

thank you.

I'd be happy to post logs if I knew where they were.

**Comment by muammar** [comment]
Were you able to solve this?. There was a report the other day: #12. Did you try with the `master` branch instead of the package?.

**Comment by chasgithub** [comment]
I was not. I saw issue 12.  I do not have pulseaudio-dlna installed (that I am aware of) just the pulseaudio volume control so that part of the discussion did not seem to apply.  As to using the master branch, I can’t.  I don’t have a build environment, so I need package installer.

 

Just for kicks though, I changed from wifi connection to a plugged in Ethernet.  This works!  So it may be the related to that issue in the router discussion.  Still no sound, but I can see the devices, so progress.

 

So perhaps should change the issue to no devices found **when connected by wifi** .  

 

Thanks for asking.  Same problem persisting though.

**Comment by muammar** [comment]
Do you have more progress on this?. Are you getting any audio? I uploaded to debian a new version of the package, and I think that as for now it should have been synced in Ubuntu.

**Comment by chasgithub** [comment]
The latest I see is 3.6-3. It still does not discover devices when connected by wifi.

 

I have been able to cast music to devices however.  There is some odd behavior, sometimes works, sometimes doesn’t,  I select one speaker and I get two.  I change speakers and the app crashes, etc.  If you would like input on debugging, I’d be glad to help.  I’m going to see if I can get a stable configuration going without futzing with it too much.  If so, and I can just leave that running, I’ll be happy.

 

Thanks for the help.  As I said, if you want data, let me know.

**Comment by muammar** [comment]
On Wed, Feb 22, 2017 at 5:48 PM, chasgithub <notifications@github.com> wrote:
>
> The latest I see is 3.6-3. It still does not discover devices when connected by wifi.
>
>

You can grab latest from here:
https://launchpad.net/ubuntu/+source/mkchromecast/0.3.7+git20170130-2/+build/12028694

>
> I have been able to cast music to devices however. There is some odd behavior, sometimes works, sometimes doesn’t, I select one speaker and I get two. I change speakers and the app crashes, etc. If you would like input on debugging, I’d be glad to help. I’m going to see if I can get a stable configuration going without futzing with it too much. If so, and I can just leave that running, I’ll be happy.
>
>
>
> Thanks for the help. As I said, if you want data, let me know.

That would be great if you could paste the errors here. Thank you.

**Comment by muammar** [comment]
I am closing this report. Please feel free to reopen it if the issue has not been fixed. Thanks.
