### ISSUE TITLE
Choppy video/audio

### ISSUE THREAD

**Issue by Silent-Hunter** [muammar/mkchromecast#49]
When I use this to cast a video, it will pause for a split second every 5 to 10 seconds or so. Audio and video will stay in sync however.

Other players such as stream2chromecast and castnow don't have this issue, but I prefer mkchromecast because when I press q, playback stops immediately, whereas the others keep playing until the chromecast's buffer empties.

**Comment by muammar** [comment]
Thanks for your report. I think that the ffmpeg commands currently used are not appropriate. I will try to use [H.264](https://trac.ffmpeg.org/wiki/Encode/H.264) to see if that improves. [I also have this in node](https://github.com/muammar/mkchromecast/blob/master/nodejs/html5-video-streamer.js), but I haven't had the time to implement it. I hope to get back to this soon.

**Comment by Silent-Hunter** [comment]
Oh, and I neglected to mention I'm using Gentoo Linux.

**Comment by muammar** [comment]
> Oh, and I neglected to mention I'm using Gentoo Linux.

Thanks for that information. But you know, yesterday I tried in macOs
and I was having the issue you described.




-- 
Muammar El Khatib.
http://muammar.me

**Comment by Silent-Hunter** [comment]
Oh, well should I try a different encoder? I'm using this to play video
files, not cast system sound.

**Comment by muammar** [comment]
@Silent-Hunter Could you test `devel` branch?. I am testing libx264 and it is working well however CPU usage is high (maybe related to `-preset veryfast -tune zerolatency` options).

**Comment by Silent-Hunter** [comment]
That works! It stutters a few times at the beginning, and then runs
smoothly. I didn't notice excessive CPU usage, but I have a rather powerful
CPU.

**Comment by muammar** [comment]
>That works! It stutters a few times at the beginning, and then runs
smoothly. I didn't notice excessive CPU usage, but I have a rather powerful
CPU.

Glad to know it worked. It happens the same for me, it stutters only at the beginning but then it goes smoothly. The problem with CPU usage I fixed in a later commit. I will keep trying to improve the ffmpeg command to get things better. But so far, it is acceptable.

**Comment by Silent-Hunter** [comment]
I just tested the stable version I was using, and it does the same thing.
The stuttering happens in different spots, but it stops after a short
while.

**Comment by muammar** [comment]
Hi @Silent-Hunter. This may be of your interest: https://github.com/muammar/mkchromecast/commit/1df82f67c5d6ab9375957a2eb085476997f5351d. Does it work for you?.

**Comment by muammar** [comment]
Example: 

```
python3 mkchromecast.py --video -i ~/Desktop/S07E14.HDTV.x264-SVA.mkv --control --encoder-backend node
```

**Comment by Silent-Hunter** [comment]
Unfortunately, it now does this:

```
mkchromecast --name smartcast --video -i Video/Movies/bbb_sunflower_1080p_60fps_normal.mp4 --control --encoder-backend node
Mkchromecast v0.3.7
Starting Video Cast Process...
Starting Node
Traceback (most recent call last):
  File "mkchromecast.py", line 252, in <module>
    mk()
  File "mkchromecast.py", line 55, in __init__
    self.cast_video()
  File "mkchromecast.py", line 129, in cast_video
    mkchromecast.video.main()
  File "/home/silent/.mkchromecast/mkchromecast/video.py", line 276, in main
    p = subprocess.Popen(webcast)
  File "/usr/lib64/python3.4/subprocess.py", line 856, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1460, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
```

**Comment by Silent-Hunter** [comment]
In addition, it also no longer casts video at all using ffmpeg backend either.

**Comment by Silent-Hunter** [comment]
Well, now it does this:

```
mkchromecast --name smartcast --video -i Video/Movies/bbb_sunflower_1080p_60fps_normal.mp4 --control --encoder-backend node
Mkchromecast v0.3.7
Starting Video Cast Process...
Starting Node
Traceback (most recent call last):
  File "mkchromecast.py", line 252, in <module>
    mk()
  File "mkchromecast.py", line 55, in __init__
    self.cast_video()
  File "mkchromecast.py", line 129, in cast_video
    mkchromecast.video.main()
  File "/home/silent/.mkchromecast/mkchromecast/video.py", line 276, in main
    p = subprocess.Popen(webcast)
  File "/usr/lib64/python3.4/subprocess.py", line 856, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1460, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'nodejs'
```

I may be missing some nodejs-python bindings?

**Comment by muammar** [comment]
Oh, yes, you have to install node in your distribution.

**Comment by muammar** [comment]
> EDIT: Wait, I'm using Gentoo, the executable is still called node on there, not nodejs.

LOL.What a problem. I use debian and they call it nodejs. Let me try to figure it out :). Thanks for your fast replies.

**Comment by Silent-Hunter** [comment]
I have it installed, but on gentoo the node executable is called 'node', on debian it's 'nodejs'. It looks like mkchromecast is trying to call 'nodejs' not 'node'. I'll try updating nodejs and see if that fixes it..

**Comment by muammar** [comment]
yes, for the moments. I will try to write something to guess what the name of the binary is. Sorry about that :).

**Comment by Silent-Hunter** [comment]
Well, it still wants to call it node, but I can make a symlink for now. Thanks for the help!

**Comment by Silent-Hunter** [comment]
OK, so it works great! No stuttering at all. But it DOES require some special care with the file path.

```
mkchromecast --name smartcast --video -i Video/Movies/bbb_sunflower_1080p_60fps_normal.mp4 --control --encoder-backend node

fs.js:967
           binding.stat(pathModule._makeLong(path), statValues);
                                                                          ^

                                                                           Error: ENOENT: no such file or directory, stat 'Video/Movies/bbb_sunflower_1080p_60fps_normal.mp4'
                                                                                                                                                                                 at Object.fs.statSync (fs.js:967:11)
                           at Server.<anonymous> (/home/silent/.mkchromecast/nodejs/html5-video-streamer.js:11:17)
                                                                                                                      at emitTwo (events.js:106:13)
                                                                                                                                                       at Server.emit (events.js:194:7)
                                                                                                                                                                                           at parserOnIncoming (_http_server.js:565:12)
                                             at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

The above does not work. However:

`mkchromecast --name smartcast --video -i /home/silent/Video/Movies/bbb_sunflower_1080p_60fps_normal.mp4 --control --encoder-backend node`

That works just fine.

`mkchromecast --name smartcast --video -i ../Video/Movies/bbb_sunflower_1080p_60fps_normal.mp4 --control --encoder-backend node`

Also works.

However I should be clear, I did make a script to run mkchromecast, mkchromecast.sh:

```
#!/bin/sh

cd /home/silent/.mkchromecast
python3 mkchromecast.py "$@"
cd -
```

So that may be causing the problem, not sure.

**Comment by muammar** [comment]
Now you shouldn't need the symlink.

Thanks for the information about relative paths not working. I will test that when I am back from work.

**Comment by Silent-Hunter** [comment]
No don't bother, that was my stupid script being dumb, nothing wrong with your program.

**Comment by muammar** [comment]
@Silent-Hunter if you agree then, I can close this report. 

There are still things to sort out, like how to have subtitles working and that kind of stuff. But I am very happy that now I can watch movies without any problems :).

**Comment by Silent-Hunter** [comment]
Subtitles would be nice, yes! And sure, you can close it.
