### ISSUE TITLE
"AttributeError: 'module' object has no attribute 'get_chromecasts_as_dict'" when launching

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [muammar/mkchromecast#51]
Hi, I tried to use mkchromecast and I encountered this error:

```
$ mkchromecast
mkchromecast v0.3.6
Creating pulseaudio sink...
Open pavucontrol and select the mkchromecast sink.
Starting local streaming server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 60, in <module>
    cc.initialize_cast()
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 94, in initialize_cast
    self.cclist = list(pychromecast.get_chromecasts_as_dict().keys())
AttributeError: 'module' object has no attribute 'get_chromecasts_as_dict'
$ 
```

### Operating System
Ubuntu 16.04 AMD64

### mkchromecast
I installed the following packages from the release page using the `gdebi` utility

* mkchromecast_0.3.6-3_all.deb
* mkchromecast-pulseaudio_0.3.6-3_all.deb

Note that in order to bypass the python-pychromecast missing dependency I crafted and installed a dummy python-pychromecast python using equivs tool then install PyChromecast using `sudo pip install pychromecast`

### PyChromecast (from pip, which appears to be installed under `/usr/local/lib/python2.7/dist`)
```shell
$ pip list | grep PyChromecast
PyChromecast (0.8.0)
```

### Python
```shell
$ python --version
Python 2.7.12
```

### Locale
```
$ locale
LANG=zh_TW.UTF-8
LANGUAGE=zh_TW:zh_HK:zh_CN:en_US:en
LC_CTYPE="zh_TW.UTF-8"
LC_NUMERIC=zh_TW.UTF-8
LC_TIME=zh_TW.UTF-8
LC_COLLATE="zh_TW.UTF-8"
LC_MONETARY=zh_TW.UTF-8
LC_MESSAGES="zh_TW.UTF-8"
LC_PAPER=zh_TW.UTF-8
LC_NAME=zh_TW.UTF-8
LC_ADDRESS=zh_TW.UTF-8
LC_TELEPHONE=zh_TW.UTF-8
LC_MEASUREMENT=zh_TW.UTF-8
LC_IDENTIFICATION=zh_TW.UTF-8
LC_ALL=
```

### Working Directory
/home/Lin-Buo-Ren

**Comment by muammar** [comment]
Hi. This is related to #32. You can try downloading this ubuntu package https://launchpad.net/ubuntu/+source/mkchromecast/0.3.7+git20170130-2/+build/12028694. Let me know if it works for you.

**Comment by Lin-Buo-Ren** [comment]
Hmm...  I somehow failed to find the issue before filing a new one, thanks for the heads-up, I've been able to use mkchromecast for now with a 3~10 seconds output delay.

**Comment by muammar** [comment]
@Lin-Buo-Ren to improve delay, try using a lossless codec like `wav` or `flac`. I haven't found a way to reduce delay when using lossy audio formats.
