### ISSUE TITLE
VPN problem/FAQ suggestion

### ISSUE THREAD

**Issue by kxxvii** [muammar/mkchromecast#55]
I had some trouble getting mkchromecast working om Debian and after some troubleshooting I figured out that OpenVPN was the problem. Passing  ```--host local-ip-adress``` solved my problem.

This might just be me being dense but a word or two about this in the FAQ, kind of like the comment about UFW/port 5000, could have saved me some time.

**Comment by muammar** [comment]
Thank you, this is a nice suggestion. See: https://github.com/muammar/mkchromecast/wiki/FAQ#i-am-using-a-vpn-how-can-i-cast-with-mkchromecast.
