### ISSUE TITLE
dynamically launching mkchromecast

### ISSUE THREAD

**Issue by mtcliff79** [muammar/mkchromecast#57]
If I try to dynamically launch mkchromecast (mkchromecast.py -n mydevice) in a non blocking method (subprocess.Popen, os.system) also using the & option. the chomecast will never connect. works perfectly from terminal.

what I would like to do is control mkchromecast remotely from a phone for example. I am trying to write a basic python script with flask to control over http. Do you have any suggestions.

**Comment by muammar** [comment]
@mtcliff79 interesting question. Probably, this `try` block here https://github.com/muammar/mkchromecast/blob/master/mkchromecast.py#L242 is causing the problems. I will do some tests, and I will get back to you.

**Comment by muammar** [comment]
I have the package installed in debian, and I did this:

```
import subprocess

command = ['mkchromecast', '-n', 'MonsiTV']

process = subprocess.Popen(command)
poutput, perror = process.communicate()
```

It worked for me. Does something like that works for you?.

**Comment by mtcliff79** [comment]
When I run this code without any additional code I get this:

usage: mkchromecast [-h] [-b BITRATE] [--chunk-size CHUNK_SIZE] [-c CODEC]
                    [--config] [--debug] [-d]
                    [--encoder-backend ENCODER_BACKEND] [-n] [--notifications]
                    [-r] [--reboot] [-s] [--sample-rate SAMPLE_RATE] [-t]
                    [--update] [-v] [--volume] [-y YOUTUBE]
mkchromecast: error: unrecognized arguments: mychromecast

**Comment by muammar** [comment]
Can you paste the code here?.

**Comment by mtcliff79** [comment]
Running this on ubuntu.

Code is below:

#!/usr/bin/env python
import subprocess
command = ['mkchromecast', '-n', 'mychromecast']
process = subprocess.Popen(command)
poutput, perror = process.communicate()

**Comment by muammar** [comment]
I am using debian unstable, and running the code you pasted works:

```
muammar@zarathustra /tmp 
  % python example.py                                                                                                                                  !10010
Mkchromecast v0.3.7
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz
PID of main process: 4295
PID of streaming process: 4302
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 
Information about  CCA
 
DeviceStatus(friendly_name=u'CCA', model_name=u'Chromecast Audio', manufacturer=u'Google Inc.', api_version=(1, 0), uuid=UUID('9a08e633-7eb4-2352-ad5d-110e23f6c3b6'), cast_type='audio')
 
Status of device  CCA
 
CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.10000000149011612, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
The IP of CCA is: 192.168.1.181
Your local IP is: 192.168.1.151
 
The media type string used is: audio/mpeg
 
Cast media controller status
 
CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.10000000149011612, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
Remember to open pavucontrol and select the mkchromecast sink.

Ctrl-C to kill the Application at any Time

192.168.1.181 - - [16/Apr/2017 12:19:14] "GET /stream HTTP/1.1" 200 -
```

```
muammar@zarathustra /tmp 
  % cat example.py                                                                                                                                     !10011
#!/usr/bin/env python
import subprocess
command = ['mkchromecast', '-n', 'CCA']
process = subprocess.Popen(command)
poutput, perror = process.communicate()

```

In your case, for some reason, 'mychromecast' is taken as an argument and not as a `str` for the `-n` option.

**Comment by muammar** [comment]
I will close this due to inactivity. Please feel free to re-open it.
