### ISSUE TITLE
Command Line Control on Mac OS

### ISSUE THREAD

**Issue by adamrhoades** [muammar/mkchromecast#59]
Can anyone point me in the right direction of how to send commands in Mac Os Sierra's Terminal to initiate a stream to a specific chromecast audio group? 

Thanks in advance.

**Comment by muammar** [comment]
You get into the cloned repo and execute:

```
python mkchromecast.py -s
```

The `-s` flag will let you select chromecast (and groups) from a list. For more options `python mkchromecast.py -h`.

**Comment by adamrhoades** [comment]
Many thanks, I've got that working now, is there any way to specify the group before it scans the network?

I want create an automation that plays my radio stream to the whole house

**Comment by muammar** [comment]
Sure, you can pass `-n NameOfMyGroup`. The `-n` flag lets you overpass the discovery process and go straight to the group or google cast device.
