### ISSUE TITLE
A small improvement for the "Linux based installation" section on your website :)

### ISSUE THREAD

**Issue by Maccer1** [muammar/mkchromecast#68]
This is the actual state of that section:

> Mkchromecast is available in the official Debian and Ubuntu repositories. You need to install it by executing:  
>      sudo apt-get install mkchromecast  
>
>Alternatively, you can download the latest deb package here, and install it as follows:  
>
>     sudo dpkg -i mkchromecast_$VERSION_all.deb
>
>where $VERSION = X.Y.Z-Rev, e.g.: 0.2.6-1. Then, if the dependencies are not available you have to do:  
>
>     sudo apt-get -f install
>
>To pull the needed dependencies to cast using pulseaudio or ALSA, please install `mkchromecast-pulseaudio` or `mkchromecast-alsa` respectively.
>
>This should work in Debian Unstable and Testing. If you find any problems, please report it here.`

What I propose is:

>Mkchromecast is available in the official Debian and Ubuntu repositories. You need to install it by executing:  
>
>       sudo apt install mkchromecast  
>
>Alternatively, you can download the latest deb package here, and install it as follows:  
>
>       sudo apt -f install ./mkchromecast_$VERSION_all.deb
>
>To pull the needed dependencies to cast using pulseaudio or ALSA, please install `mkchromecast-pulseaudio` or `mkchromecast-alsa` respectively.
>
>This should work in Debian Unstable and Testing. If you find any problems, please report it here.`

The changes are using `apt` instead of `apt-get` and using just one command to install and check dependencies.

**Comment by muammar** [comment]
Great! thanks for this addition!. Would you mind creating a pull request to add these changes?.

**Comment by Maccer1** [comment]
I think I've done it.  It's the first time I do a pull request so It may have some mistakes...

**Comment by muammar** [comment]
@Maccer1 thank you. I have merged your changes in `master`.
