### ISSUE TITLE
Problems with accentuation

### ISSUE THREAD

**Issue by mhalano** [muammar/mkchromecast#7]
My Chromecast is named with a non-ascii character, so this error occurs:
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 55, in <module>
    cc.initialize_cast()
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 95, in initialize_cast
    print(str(self.index)+'      ', str(device))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 11: ordinal not in range(128)
Could you fix that?

Thanks!

**Comment by muammar** [comment]
@mhalano I see you are using the debian package, but I would be glad if you could test from the github repository? I think commit c6c646eb0580a2e7882efa10950916ea26f81db2 should fix this. Tell me if it works.
