### ISSUE TITLE
Dual sound issue

### ISSUE THREAD

**Issue by siddharthalodha** [muammar/mkchromecast#73]
I tried it for the first time with Google Home. 

1. There's a delay of around 3-4 seconds on default settings.
2. There's sound coming from both the devices : Macbook as well as Google home.

I also installed latest version of Soundflower.

I am running MacOS Sierra 10.12.5 Beta.

**Comment by muammar** [comment]
> I also installed latest version of Soundflower.

Did you reboot after install?.  I remember once a similar problem with soundflower that was solved by just rebooting. If the problem persists, try to check in the preferences that the Audio input is not set to the microphone. Let me know if this works.  Thanks.

**Comment by siddharthalodha** [comment]
Did a reboot also. Input automatically switched to microphone. Switched it back to soundflower. Still the same.

**Comment by ao-il** [comment]
The info provided is not enough to understand the problem IMO. (Settings/Screenshots?) What kind of sound? Is it the feedback sounds from the CC device? If so make sure to disable feedback sounds from the device.

**Comment by muammar** [comment]
I will close this report. Feel free to reopen it if needed.
