### ISSUE TITLE
Feature request: Mac app, run as tray icon, no cmd+tab icon

### ISSUE THREAD

**Issue by mydudechris** [muammar/mkchromecast#75]
Love the app, thanks for building it! Would it be possible to kill the Tab screen icon and just let this run as a tray app? Or at least add an option to hide the tab functionality?

**Comment by muammar** [comment]
Yes, it sounds good. I will try to implement this. It does not seem to be complicated according to this. https://stackoverflow.com/questions/5533460/how-to-hide-a-pyqt-applications-icon-from-mac-os-x-dock/8579983

**Comment by muammar** [comment]
This is done now. For next release you will see the change. Thanks.
