### ISSUE TITLE
Please distribute the desktop file and man page here

### ISSUE THREAD

**Issue by polyzen** [muammar/mkchromecast#76]
This would make it easier for package maintainers of other distros (to source the latest copies) and for people to contribute to them.

**Comment by polyzen** [comment]
It might also be okay to set +x on mkchromecast.py in this repo.

**Comment by muammar** [comment]
That's a good idea. I think I will distribute the manual in a new directory called `man`. As for the desktop file, should it be inside an `applications` folder or something like that?.

**Comment by muammar** [comment]
@polyzen I have done it now. I created a `man` directory for the manual and then the `.desktop` is in the root of Mkchromecast.

**Comment by polyzen** [comment]
Thank you very much.

**Comment by muammar** [comment]
@polyzen you are welcome. I was wondering -- do you plan to make a package to another distro?.

**Comment by polyzen** [comment]
Not necessarily -- there's already a package for Arch Linux, following the devel branch. I will make one for the releases.

**Comment by muammar** [comment]
I see. Someone requested a RPM package, but Fedora website is not very clear about it.

**Comment by polyzen** [comment]
Ah, I haven't done RPM packaging before.

**Comment by muammar** [comment]
Me neither.
