### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by AMB85** [muammar/mkchromecast#77]
Hi-
When I got to start up mkchromecast I get the following error:

ubuntu@ubuntu:~/mkchromecast$ python3 mkchromecast.py
Traceback (most recent call last):
  File "mkchromecast.py", line 8, in <module>
    from mkchromecast.cast import *
  File "/home/ubuntu/mkchromecast/mkchromecast/cast.py", line 14, in <module>
    import pychromecast
ImportError: No module named 'pychromecast'

Any thoughts on what I may be missing?

**Comment by muammar** [comment]
> ImportError: No module named 'pychromecast'

You need `pychromecast` module. 

These are the dependencies: 

```
Depends: python:any (>= 2.7.5-5~), python-flask, python-pychromecast,
python-psutil, vorbis-tools (>= 1.4.0), sox (>= 14.4.1), lame (>=
3.99.0), flac (>=  1.3.0), python-pyqt5, youtube-dl, nodejs,
gir1.2-notify-0.7
```

If you are in Ubuntu < 16.10, then you need to use `pip` to install the dependencies as described here: https://github.com/muammar/mkchromecast#python.
