### ISSUE TITLE
Why is flac tied to mkchromecast?

### ISSUE THREAD

**Issue by ao-il** [muammar/mkchromecast#78]
`apt-get and dpkg`
Flac and mkchromecast don't install or uninstall separately. Is this a bug?

**Comment by muammar** [comment]
If I install on Debian, mkchromecast pulls the following:

```
  % sudo apt-get install mkchromecast                                                                                                                  !10128
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  flac gir1.2-notify-0.7 lame libao-common libao4 libopencore-amrnb0 libopencore-amrwb0 libsox-fmt-alsa libsox-fmt-base libsox2 python-blinker python-click
  python-colorama python-flask python-itsdangerous python-jinja2 python-markupsafe python-netifaces python-openssl python-protobuf python-psutil
  python-pychromecast python-pyinotify python-requests python-urllib3 python-werkzeug python-zeroconf sox vorbis-tools
Suggested packages:
  libesd0 | libesd-alsa0 libsox-fmt-all libav-tools mkchromecast-pulseaudio mkchromecast-alsa python-blinker-doc python-flask-doc python-jinja2-doc
  python-openssl-doc python-openssl-dbg python-psutil-doc python-pyinotify-doc python-socks python-ntlm python-genshi python-greenlet python-redis
  python-pylibmc | python-memcache python-termcolor python-watchdog python-werkzeug-doc
The following NEW packages will be installed:
  flac gir1.2-notify-0.7 lame libao-common libao4 libopencore-amrnb0 libopencore-amrwb0 libsox-fmt-alsa libsox-fmt-base libsox2 mkchromecast python-blinker
  python-click python-colorama python-flask python-itsdangerous python-jinja2 python-markupsafe python-netifaces python-openssl python-protobuf
  python-psutil python-pychromecast python-pyinotify python-requests python-urllib3 python-werkzeug python-zeroconf sox vorbis-tools
0 upgraded, 30 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/3,982 kB of archives.
```

If trying to install only flac without having mkchromecast:

```
 % sudo apt-get install flac                                                                                                                          !10129
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  flac
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/153 kB of archives.
After this operation, 438 kB of additional disk space will be used.
Selecting previously unselected package flac.
(Reading database ... 224741 files and directories currently installed.)
Preparing to unpack .../flac_1.3.2-1_amd64.deb ...
Unpacking flac (1.3.2-1) ...
Setting up flac (1.3.2-1) ...
Processing triggers for man-db (2.7.6.1-2) ...

muammar@nuc ~/tmp/krr
  % aptitude search mkchromecast                                                                                                                       !10131
p   mkchromecast                                                           - Cast your Linux audio or video to your Google Cast devices
p   mkchromecast-alsa                                                      - ALSA dependencies to cast with mkchromecast
p   mkchromecast-gstreamer                                                 - GStreamer dependencies to cast with mkchromecast
p   mkchromecast-pulseaudio                                                - Pulseaudio dependencies to cast with mkchromecast
```

**Comment by polyzen** [comment]
If you try to uninstall a package that is a dependency (`flac`) of another packge (`mkchromecast`), you either have to uninstall both or force it (normally leading to breakage in the packages that depend on it).

**Comment by muammar** [comment]
@polyzen that is correct. The only way this could be changed is adding `flac` as a `Suggests` instead of `Depends` but I don't want that. IMO, all codecs that are supported by this app, and that are free software,  should be installed by default to have full functionality.

**Comment by ao-il** [comment]
I get that mkchromecast should include flac but why should flac depend on mkchromecast? I think it is better to incorporate flac internally instead, like other applications that handle flac format even without it being installed.

**Comment by muammar** [comment]
> I get that mkchromecast should include flac but why should flac depend on mkchromecast?

Flac does not depend on mkchromecast.

**Comment by polyzen** [comment]
@ao-il, see https://packages.debian.org/buster/flac.

**Comment by muammar** [comment]
@polyzen I was about to paste the same URL. Thanks.

**Comment by ao-il** [comment]
Ok, maybe that's not the correct way to say it, but why does uninstalling mkchromecast also imply flac removal, when mkchromecast met flac on my machine?

Thanks @polyzen for the link. Perhaps mkchromecast should use libflac instead?

**Comment by ao-il** [comment]
Sorry, that was a lie, I take it back. I can uninstall mkchromecast without uninstalling flac, but not the other way round.

**Comment by polyzen** [comment]
> Perhaps mkchromecast should use libflac instead?

The `flac` program doesn't appear to be called directly, so I imagine so.

**Comment by polyzen** [comment]
GitHub search has failed me once again: https://github.com/muammar/mkchromecast/blob/master/mkchromecast/audio.py#L597-L598

**Comment by muammar** [comment]
parec is called here https://github.com/muammar/mkchromecast/blob/master/mkchromecast/audio.py#L595

**Comment by muammar** [comment]
@polyzen correct.

**Comment by ao-il** [comment]
I see that libflac can't be called directly, but since libflac is the codec and not flac, I think it is safer and better to use the latter, like using liblame instead of lame, so that any external modification of the wrapper tool does not affect the functionality of mkchromecast. This means you'll need to device your own means of interfacing with the codecs.

**Comment by ao-il** [comment]
Sorry, I meant it is safer and better to use the former.

**Comment by ao-il** [comment]
Why does this issue have an `invalid` label? Kindly explain.

**Comment by ao-il** [comment]
Did not mention this in the beginning, maybe it'll help understand this issue. You maybe wondering why I would ever want to uninstall flac. This was because I wanted to upgrade my flac version to the latest, so I needed to remove the old version first before upgrading to the newest. Removing the old version required that I also remove mkchromecast which was what upset me. So, now you know why. It wasn't really a big deal since I was able to force the removal, but my aim was to suggest an improvement. It is fine by me to close the issue if you wish.

**Comment by polyzen** [comment]
> Why does this issue have an invalid label? Kindly explain.

What you had initially described was just a lack of understanding, not a valid bug.

> This was because I wanted to upgrade my flac version to the latest, so I needed to remove the old version first before upgrading to the newest.

`apt update` then `apt upgrade` (or `apt install flac` for just the one package, apparently) is how to upgrade.

https://www.debian.org/doc/manuals/debian-faq/ch-pkgtools.en.html#s-apt-get

**Comment by muammar** [comment]
> Why does this issue have an invalid label? Kindly explain.

What you wrote in the first message was not a valid bug. 

@polyzen is right. You should `update` and then `upgrade`. **Mkchromecast** depends on `flac >=1.3.0` see https://github.com/muammar/mkchromecast/blob/debian/debian/control#L25. 
Therefore, installing newer versions should not break anything. 

According to `flac`'s manual:

> flac is a command-line tool for encoding, decoding, testing and analyzing FLAC streams.

I don't see the point of implementing an interface for this if there is already something that does it. It would require more work and I don't have so much time lately.

I will proceed to close this report.

**Comment by muammar** [comment]
I forgot to mention, I would be more than glad to receive a PR with such an improvement!. :)

**Comment by ao-il** [comment]
I understand that it isn't a bug, since mkchromecast was intended to use flac in that manner. Updating before upgrading has nothing to do with it, or did you mean that if I updated the package database before upgrading flac,  then I would not have had that issue of not being able to remove flac without also removing mkchromecast? Why did it not affect ffmpeg, audacious and audacity the same way? They also handle flac codec. I understand that it is of lowest priority to fix this, but was expecting to see something like `enhancement` or `help wanted`, rather than `invalid`.

**Comment by muammar** [comment]
>I understand that it isn't a bug, since mkchromecast was intended to use flac in that manner. Updating before upgrading has nothing to do with it, or did you mean that if I updated the package database before upgrading flac, then I would not have had that issue of not being able to remove flac without also removing mkchromecast? 

I don't know if you are used to `apt`, but when you upgrade your system, normally the steps are:

```
apt-get update
apt-get upgrade
```

In that way, the package manager will uninstall/install packages without breaking things. The other way around, using for instance `dpkg -i`, is to download your new version of the package and when doing `dpkg -i` the package manager will uninstall/install without breaking anything. There is no need to uninstall manually. 

Let's suppose you have `ffmpeg` installed in your debian based distro. That package depends on `libswscale4`, and let's try to uninstall it to then install another updated version:

```
muammar@nuc ~ 
  % sudo apt-get remove libswscale4                                                               !10009
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  freepats gimp-data libamd2 libass5 libavformat57 libbabl-0.1-0 libbs2b0 libcamd2 libccolamd2
  libcholmod3 libchromaprint1 libdc1394-22 libdca0 libde265-0 libdvdnav4 libdvdread4 libebur128-1
  libfaad2 libflite1 libfluidsynth1 libgimp2.0 libgme0 libgstreamer-plugins-bad1.0-0 libkate1
  liblilv-0-0 libllvm3.9 libmetis5 libmjpegutils-2.1-0 libmms0 libmodplug1 libmpcdec6
  libmpeg2encpp-2.1-0 libmpg123-0 libmplex2-2.1-0 libofa0 libopenal-data libopenal1 libopencv-core2.4v5
  libopencv-flann2.4v5 libopencv-imgproc2.4v5 libopencv-video2.4v5 libopenmpt0 libpostproc54 libraw16
  librubberband2 libsbc1 libsdl2-2.0-0 libserd-0-0 libsndio6.1 libsord-0-0 libsoundtouch1 libspandsp2
  libsratom-0-0 libsrtp0 libtbb2 libuchardet0 libumfpack5 libva-wayland1 libvo-aacenc0 libvo-amrwbenc0
  libvulkan1 libwildmidi-config libwildmidi2 libzbar0
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  ffmpeg gimp gstreamer1.0-plugins-bad libavdevice57 libavfilter6 libgegl-0.3-0 libopencv-calib3d2.4v5
  libopencv-features2d2.4v5 libopencv-highgui2.4-deb0 libopencv-objdetect2.4v5 libswscale4 mpv
0 upgraded, 0 newly installed, 12 to remove and 0 not upgraded.
After this operation, 44.2 MB disk space will be freed.
Do you want to continue? [Y/n] 

```

As you can see, `ffmpeg` will be removed doing this. That is what @polyzen mentioned above. 

>Why did it not affect ffmpeg, audacious and audacity the same way? They also handle flac codec.

Because none of them depend on flac.
 
https://packages.debian.org/sid/ffmpeg
https://packages.debian.org/sid/audacity

Audacity depends on `libflac`, but as I mentioned, I don't see the point of implementing something that flac already does. 

> I understand that it is of lowest priority to fix this, but was expecting to see something like enhancement or help wanted, rather than invalid.

Implementing this would probably require learning some python bindings to operate with libflac. In my experience with python Qt5 bindings, it can be a real pain maintaining packages with bindings when libraries change. I could let it open, and tag it as `enhancement`.

**Comment by ao-il** [comment]
Ok, I accept your arguments.
