### ISSUE TITLE
screen casting with ffmpeg?

### ISSUE THREAD

**Issue by Northcode** [muammar/mkchromecast#82]
Is it possible to use the ffmpeg backend to grab the screen and screencast it?

Would be helpful for presentations etc.

You can use x11grab on Linux and avfoundation on macOS:
https://trac.ffmpeg.org/wiki/Capture/Desktop

Is this possible currently with some custom arguments or do you need to implement something?

**Comment by muammar** [comment]
I tried the other day, and then the `python-flask` server was failing in some way. But let's give it a try again.

**Comment by muammar** [comment]
I have something working. You can pull the `devel` branch. An example:

```
python3 mkchromecast.py --video --screencast --resolution 2k
```

It is not perfect, but I would be glad if you would let me know that it works?. Step by step we could improve this!. Thanks.

**Comment by Northcode** [comment]
Nice. I'll have a look. The problem is I just got on holiday and I won't
have a chromecast until around the 30th or so. But I'll look into it then!

Thanks for looking into it!

**Comment by Northcode** [comment]
tested it now, sorry it took so long, it seems to work although I am getting an almost 5 second delay. Is that due to ffmpeg or the protocol do you think? My chromecast is connected over wifi

Used:
`python mkchromecast.py --video --screencast --resolution 1080p -s`

**Comment by sambokai** [comment]
I would suggest to close this issue, since the functionality is implemented and the issue is blocking the release. Concerning the 5 second delay we should open a separate issue for the next release. Agree?

**Comment by Northcode** [comment]
Agreed

**Comment by monperrus** [comment]
For the record, got screencasting to work thanks to #104.

`python3 mkchromecast.py --video --command 'ffmpeg -f lavfi -i anullsrc -f x11grab -r 25 -s 1920x1080 -i :0.0+0,0 -vcodec libx264 -preset ultrafast -tune zerolatency -maxrate 10000k -bufsize 20000k -pix_fmt yuv420p -g 60 -f mp4 -max_muxing_queue_size 9999 -movflags frag_keyframe+empty_moov pipe:1'`

(note the `-f lavfi -i anullsrc` to disable audio)
