### ISSUE TITLE
Error when running mkchromecast command

### ISSUE THREAD

**Issue by longunmin** [muammar/mkchromecast#85]
Hi,

I hope it is alright to post this problem here, but I installed via debian package without any errors and when I run the mkchromecast command i get the below error. What am I missing? Thank you!

```
pi@raspberrypi:~ $ mkchromecast
Mkchromecast v0.3.7
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 270, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 51, in __init__
    self.audio_linux()
  File "/usr/bin/mkchromecast", line 65, in audio_linux
    create_sink()
  File "/usr/share/mkchromecast/mkchromecast/pulseaudio.py", line 28, in create_sink
    stderr=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by muammar** [comment]
The creation of the sink is failing. Do you have `pulseaudio-utils` installed on your system?.

**Comment by longunmin** [comment]
That did it! Thank you and sorry for the silly question!

**Comment by muammar** [comment]
@longunmin that is not silly question. How did you install it? Using `apt-get`?. I think you also needed to install `mkchromecast-pulseaudio` to pull those dependencies. If that was not clear in some way when you tried the installation, then I should update the README.

**Comment by longunmin** [comment]
Yeah I installed using `apt-get` and then it started right up. I installed using the debian package, and thought I had followed everything in the README, but it is likely I missed the instructions to install pulseaudio

**Comment by muammar** [comment]
It is there :)

https://github.com/muammar/mkchromecast#linux-2

I will close this report. Happy it worked for you.
