### ISSUE TITLE
ffmpeg: Too many packets buffered for output stream 0:1.

### ISSUE THREAD

**Issue by Foxboron** [muammar/mkchromecast#86]
It seems like the buffer get too big on some files. I'm unsure if this is an error inn the ffmpeg line mkchromecast uses, or this upstream issue; https://trac.ffmpeg.org/ticket/6375

I managed to get it solved with this diff. I could write a PR to enable this option incase its a bad idea to have enabled at all times.
```diff
diff --git a/mkchromecast/video.py b/mkchromecast/video.py
index 526c42d3..19b631f4 100644
--- a/mkchromecast/video.py
+++ b/mkchromecast/video.py
@@ -167,6 +167,7 @@ else:
             '-g', '60', #'-c:a', 'copy', '-ac', '2',
             #'-b', '900k',
             '-f', 'mp4',
+            '-max_muxing_queue_size', '9999',
             '-movflags', 'frag_keyframe+faststart ',
             'pipe:1'
         ]
```

Another related issue is that mkchromecast doesn't check if ffmpeg fails. So it will just continue to run without anything happening on screen.

**Comment by muammar** [comment]
@Foxboron thanks for this report. Which version of `ffmpeg` are you using?. 

>Another related issue is that mkchromecast doesn't check if ffmpeg fails. So it will just continue to run without anything happening on screen.

Good point, it would be a good idea to implement something that checks if it failed and does something.

**Comment by Foxboron** [comment]
```
λ fox@theia ~ » ffmpeg
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.1 (GCC) 20170630
```

**Comment by muammar** [comment]
> I'm unsure if this is an error inn the ffmpeg line mkchromecast uses, or this upstream issue; https://trac.ffmpeg.org/ticket/6375

I am leaning to think this hast to do with `ffmpeg`'s version. My version is

```
± % ffmpeg                                                                                        !10001
ffmpeg version 3.2.6-1+b3 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-19) 20170618
```

I am on Debian unstable.
