### ISSUE TITLE
Unmet dependencies on Ubuntu 16.04 LTS (64 bit)

### ISSUE THREAD

**Issue by jymbob** [muammar/mkchromecast#9]
`dpkg -i mkchromecast_0.3.2-1_all.deb` gives the following:
```
Unpacking mkchromecast (0.3.2-1) over (0.3.2-1) ...
dpkg: dependency problems prevent configuration of mkchromecast:
 mkchromecast depends on python-flask; however:
  Package python-flask is not installed.
 mkchromecast depends on python-pychromecast; however:
  Package python-pychromecast is not installed.
 mkchromecast depends on python-psutil; however:
  Package python-psutil is not installed.
 mkchromecast depends on sox (>= 14.4.1); however:
  Package sox is not installed.

dpkg: error processing package mkchromecast (--install):
 dependency problems - leaving unconfigured

```
python-pychromecast doesn't appear to be in the repositories.
Fetching the pychromecast deb from [here](http://ftp.br.debian.org/debian/pool/main/p/pychromecast/python-pychromecast_0.7.3-1_all.deb) then running `apt-get -f install` appears to fix it.
I've now installed it and connected to my Chromecast. Haven't actually tried sending anything yet.

**Comment by muammar** [comment]
@jymbob thanks for the report. Yes, that is expected. I will link your report in the wiki so others can benefit from this. 

I am a debian developer, and I have decided that I will upload the package to debian archives to make things easier. I have already created an [ITP for mkchromecast](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834400).

**Comment by muammar** [comment]
Package is now in debian repositories: https://packages.debian.org/unstable/mkchromecast. Once it is synced in latest ubuntu version, and all dependencies will be installed.

**Comment by muammar** [comment]
Package is now in Ubuntu: https://launchpad.net/ubuntu/+source/mkchromecast. I will close this report.

**Comment by akalongman** [comment]
@muammar 
After running `sudo dpkg -i mkchromecast_0.3.7.1-1_all.deb` I have an error:
```
Selecting previously unselected package mkchromecast.
(Reading database ... 430276 files and directories currently installed.)
Preparing to unpack mkchromecast_0.3.7.1-1_all.deb ...
Unpacking mkchromecast (0.3.7.1-1) ...
dpkg: dependency problems prevent configuration of mkchromecast:
 mkchromecast depends on python-pychromecast; however:
  Package python-pychromecast is not installed.

dpkg: error processing package mkchromecast (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 mkchromecast
```
How to install `python-pychromecast` on ubuntu 16.04?

**Comment by muammar** [comment]
Try downloading from here: https://packages.ubuntu.com/yakkety/all/python-pychromecast/download and install it manually. Tell me if it works for you. By the way, what version of Ubuntu are you using?.

**Comment by akalongman** [comment]
@muammar I am using Ubuntu 16.04. Ok mkchromecast is installed and running, but it can not find my streaming device (chromecast audio)

**Comment by muammar** [comment]
> @muammar I am using Ubuntu 16.04. Ok mkchromecast is installed and running, but it can not find my streaming device (chromecast audio)

Can you open a new issue, please?. Thanks.

**Comment by ludoo0d0a** [comment]
Hi, on my Ubuntu 16, installing python-pychromecast requires an update on python-protobuf
How to fix this ?

> Préparation du dépaquetage de python-pychromecast_0.7.3-3_all.deb ...
Dépaquetage de python-pychromecast (0.7.3-3) sur (0.7.3-3) ...
dpkg: des problèmes de dépendances empêchent la configuration de python-pychromecast :
 python-pychromecast dépend de python-protobuf (>= 3) ; cependant :
  La version de python-protobuf sur le système est 2.6.1-1.3.

**Comment by muammar** [comment]
You have two choices: 1) Follow the instructions to [install from sources](https://github.com/muammar/mkchromecast#from-sources), or 2) try installing the [missing dependency from here](https://packages.ubuntu.com/yakkety/python-protobuf) and all subsequent ones that may be missing too. 

**Mkchromecast** deb package is compatible with Ubuntu 16.10 and up.
