### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by ao-il** [muammar/mkchromecast#90]
Keep getting..
`Connection failure: Connection refused
pa_context_connect() failed: Connection refused`
Any idea why?

**Comment by muammar** [comment]
Is your pulseaudio running?.

**Comment by ao-il** [comment]
No, I don't have pulseaudio installed. 
The reason was because I ran mkchromecast without arguments and there was no audio playing.

**Comment by muammar** [comment]
Oh, I see. By default that's what is used. The reason for that is because most of Linux distros have pulseaudio by default.
