### ISSUE TITLE
Problems on Ubuntu

### ISSUE THREAD

**Issue by darkstar01uk** [muammar/mkchromecast#94]
Hi Muammar. Thanks for the hard work you have put into mkchromecast. I have a problem streaming to CCA from Kubuntu 16.04 LTS.
I installed mkchromecast as detailed here, with all the dependencies, but it doesn't work very well. I can stream to CCA using the default settings of backend=parec / bitrate=192 / sample rate=44100 but I'd like to use higher resolution streams if available. If I try to run with backend=ffmpeg, flac and higher bitrate and sample rate, then I hear the bell sound as CCA connects and my Pulseaudio volume controller shows an audio signal (the "VU meter" moves satisfactorily) and I can select mkchromecast as an output, but there is no sound output. In fact there is no outward network traffic showing, when I use the default settings I see steady outward network traffic. 
Launching mkchromecast with the -t option and opening the preferences dialogue shows ffmpeg avconv and parec as available backends, flac as a codec, bitrates up to 500 and sample rates up to 192k
Any ideas? Thanks

**Comment by muammar** [comment]
Hi, thank you very much for your message. Happy to see it is somewhat useful for you :). 

Can you post the command you were using for this?. Is ffmpeg installed (sorry for this question)?. Finally, how did you install the application (cloning, apt)?.

**Comment by darkstar01uk** [comment]
Thanks Muammar I'm away for a couple of days will answer the questions when I get home.

**Comment by darkstar01uk** [comment]
Hi Muammar

For all these examples I'm playing Bandcamp tracks in Chrome and local flac files using VLC on an Intel i7 laptop running Kubuntu 16.04. The CCA is connected by optical cable to an external DAC but the results are the same using the CCA audio out.

If start mkchromecast in a console using `python /usr/bin/mkchromecast` then it shows parec / mp3 / 192 / 44100 and streams music to CCA, starting with the CCA system bell sound. I can see and select mkchromecast as an output in pavucontrol. My network monitor shows a steady outward stream around 22 - 26 KB/s (around 192kb/s). See mk_mp3.txt

If I start mkchromecast using `python /usr/bin/mkchromecast --encoder-backend ffmpeg -c flac -b 500 --sample-rate 48000` then the console shows ffmpeg / flac / 500 / 48000, I hear the CCA bell and can select mkchromecast in pavucontrol, but there is no audible music output. My network monitor shows no outward traffic from the laptop. It seems to me (dangerous amateur assumption!) that the problem is in streaming, actually getting the signal out of my laptop, as the "sound meter" below the volume slider in pavucontrol flicks up and down as it should. It's playing music but not streaming to CCA. See mk_flac.txt

I've checked and re-installed ffmpeg.

I installed by following the instructions [here](http://www.omgubuntu.co.uk/2016/08/cast-ubuntu-desktop-audio-chromecast) dealing with dependencies from the Ubuntu repos.

Hope this helps!
[mk_flac.txt](https://github.com/muammar/mkchromecast/files/1213110/mk_flac.txt)
[mk_mp3.txt](https://github.com/muammar/mkchromecast/files/1213111/mk_mp3.txt)

**Comment by muammar** [comment]
Thanks for your report. Can you tell me if this happens with other codecs or only flac? Sorry for the delay in replying.

**Comment by darkstar01uk** [comment]
Hi. Good question! So mp3 and wav work, and output to the CCA. flac ogg and aac don't work. Weird? 
Using `python /usr/bin/mkchromecast --encoder-backend ffmpeg -c wav --sample-rate 96000` sounds good and my wireless seems happy with the traffic. 

Now why didn't I think of checking that before? :-) Thanks for your help!

**Comment by muammar** [comment]
I could look better on this, and as for now I can use `ffmpeg` with `flac` and `500k` bitrate:

```
muammar@nuc ~/github/mkchromecast [devel] 
± % python3 mkchromecast.py --encoder-backend ffmpeg -c flac -b 500 --sample-rate 48000 -n 'Chromecast Audio' --debug                                                                                       !10027
ALSA device name: None.
Google Cast name: Chromecast Audio.
backends:  ['ffmpeg', 'avconv', 'parec', 'gstreamer']
ALSA device name: None.
Google Cast name: Chromecast Audio.
backends:  ['ffmpeg', 'avconv', 'parec', 'gstreamer']
USER =muammar
PATH =/home/muammar/brown/git/ase/tools:/home/muammar/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/X11/bin:/usr/games:/home/muammar/.local/bin:/home/muammar/brown/git/ase/bin:/snap/bin
Mkchromecast v0.3.8
:::cast::: sockets method 192.168.86.158
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
:::audio::: chunk_size, frame_size, buffer_size: 64, 2048, 8192
Selected backend: ffmpeg
Selected audio codec: flac
Selected bitrate: 500k
Sample rates supported by flac are: 22050Hz, 32000Hz, 44100Hz, 48000Hz  96000Hz or 192000Hz.
Sample rate set to: 48000Hz
:::audio::: command ['ffmpeg', '-ac', '2', '-ar', '44100', '-frame_size', '2048', '-fragment_size', '2048', '-f', 'pulse', '-i', 'Mkchromecast.monitor', '-f', 'flac', '-acodec', 'flac', '-ac', '2', '-ar', '48000', '-b:a', '500k', 'pipe:']
PID of main process: 19941
PID of streaming process: 19951
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
self.cclist [[0, 'Google Home Mini', 'Gcast'], [1, 'Chromecast Audio', 'Gcast'], [2, 'MonsiTV', 'Gcast']]
def get_cc(self):
 
Information about  Chromecast Audio
 
DeviceStatus(friendly_name='Chromecast Audio', model_name='Chromecast Audio', manufacturer=None, api_version=None, uuid=UUID('9a08e633-7eb4-2352-ad5d-110e23f6c3b6'), cast_type='audio')
 
Status of device  Chromecast Audio
 
CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.10000000149011612, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
def play_cast(self):
The IP of Chromecast Audio is: 192.168.86.159
Your local IP is: 192.168.86.158
 
The media type string used is: audio/flac
 
Cast media controller status
 
CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.10000000149011612, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
Remember to open pavucontrol and select the mkchromecast sink.

Ctrl-C to kill the Application at any Time

ffmpeg version 3.4.1-1+b1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7 (Debian 7.2.0-18)
  configuration: --prefix=/usr --extra-version=1+b1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, pulse, from 'Mkchromecast.monitor':
  Duration: N/A, start: 1513913617.163243, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> flac (native))
Press [q] to stop, [?] for help
Output #0, flac, to 'pipe:':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Audio: flac, 48000 Hz, stereo, s16, 500 kb/s
    Metadata:
      encoder         : Lavc57.107.100 flac
192.168.86.159 - - [21/Dec/2017 22:33:37] "GET /stream HTTP/1.1" 200 -
```

I am closing this report but feel free to reopen it if it is not solved. 

PS. I am using the `devel` branch and will be releasing soon a new version.
