### ISSUE TITLE
[Bug] Pausing with p has a great lag (--control option)

### ISSUE THREAD

**Issue by mhham** [muammar/mkchromecast#97]
Hi there.
First of all thanks for this great software !
When I am casting a video using the `--control` option (e.g. `mkchromecast --control --video -i /path/to/video --subtitles /path/to/subtitles`) all the controls for volume work great and instantaneously, but the controls to pause and resume have some lag. Resume is quite OK, but pausing is really unreliable. It works one time out of ten, and with a great lag (~1min or more).
Cheers

**Comment by ljoli** [comment]
Hello, 
I use the following version : 
>> python mkchromecast.py -v
mkchromecast v0.3.7.1
On Linux more precisely on archlinux.
I have the same problem of @mhham .

python mkchromecast.py -y https://www.youtube.com/watch?v=LRP8d7hhpoQ   --video --control
I just can do : u , d and q

**Comment by muammar** [comment]
I think this should be fixed now.
